### ISSUE TITLE
[Android app] Error reporting from text doesn't work

### ISSUE THREAD

**Issue by wgm-gh** [Sefaria/Sefaria-Project#1000]
Using v5.14.4 on Android 11, Galaxy A10.

This page provides instructions for reporting erros from the app - https://www.sefaria.org/sheets/213949.2?lang=bi ; it reads:
> Reporting an error directly from the app
> 1. Long click on the text that contains an error.
> 2. Click on "Report Error".

...and shows a gif demo of the process. In the demo, there's a Feedback item on the list the click opens, but that is missing from the app.

By the way, a simple tap is required to open something like a context menu, not a "long click" - **or is this referring to a PC app** (I'm not aware of such existing)**?**

May be related to #999.

**Comment by HadaraRachel** [comment]
Thank you for reporting! this has been fixed. 
for any further bugs/features ideas please email hello@sefaria.org
