### ISSUE TITLE
right to left punctuation

### ISSUE THREAD

**Issue by yishairasowsky** [Sefaria/Sefaria-Project#1011]
Shalom! Thank you for all that you do!
I am using this code (found at the end of [this colab notebook](https://colab.research.google.com/drive/120l8UeczgOZbtdiGghV9a3SVm8DTKvhw?usp=sharing)):
```
import requests
section = 1
for book in ['Genesis','Mishnah_Avot']:a
    txt_url = f'http://www.sefaria.org/api/texts/{book}.{section}'
    txt_response = requests.get(txt_url)
    txt_json = txt_response.json()
    sentences = txt_json['he']
    sentences = [sentence.rstrip() for sentence in sentences]
    sentence = sentences[1]
    print(repr(sentence))
```
And I am not sure why sometimes the punctuation is correctly displayed right to left, e.g. the colon at the end of the verse in Genesis:
```
'וְהָאָ֗רֶץ הָיְתָ֥ה תֹ֙הוּ֙ וָבֹ֔הוּ וְחֹ֖שֶׁךְ עַל־פְּנֵ֣י תְה֑וֹם וְר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל־פְּנֵ֥י הַמָּֽיִם׃'
```
whereas other times the punctuation which is supposed to appear at the end actually appears at the beginning, e.g. in the verse from Mishnah_Avot:
```
'שִׁמְעוֹן הַצַּדִּיק הָיָה מִשְּׁיָרֵי כְנֶסֶת הַגְּדוֹלָה. הוּא הָיָה אוֹמֵר, עַל שְׁלשָׁה דְבָרִים הָעוֹלָם עוֹמֵד, עַל הַתּוֹרָה וְעַל הָעֲבוֹדָה וְעַל גְּמִילוּת חֲסָדִים:'
```
Please can you clarify? The reason it is important to me is for presentation purposes. I prefer this:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/39579959/189888431-27f2a024-82d9-4681-a653-492d4f9b37cf.png">
rather than this:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/39579959/189888347-260252e5-7967-4682-bb66-479a8309166e.png">
Thank you so much! By the way, if this is the wrong place to post questions like this, please let me know -- I wouldn't want to bother anybody unnecessarily.

**Comment by nsantacruz** [comment]
Hi! The Sefaria code you posted looks correct. This looks like a display issue independent of Sefaria so I'm going to close this issue. It depends on the exact way your displaying the text. E.g. if you're displaying it on a webpage, make sure `direction: rtl` is applied to the text in CSS. 

Hope this helps!

**Comment by yishairasowsky** [comment]
@nsantacruz thank you so much for the speedy reply!
I am afraid I am not sure what setting -- e.g. rtl -- I am missing; because in this image it shows that all else being equal, the two outputs bear the discrepancy in the final colon. Does this help clarify? Thank you for your valuable time!
<img width="613" alt="image" src="https://user-images.githubusercontent.com/39579959/190082052-e4bb6eba-aa83-4297-87d2-e32f99081bca.png">

**Comment by EliezerIsrael** [comment]
This is curious - seems to be something about Python's handling of bidi text.  Just to be sure, I checked `sentence[-1]` for both of these, and the result is `:`.

**Comment by yishairasowsky** [comment]
Following your lead @EliezerIsrael , I looked into the encoding format for the last character, and I see something that looks like the beginning of a solution.
```
import requests
section = 1
for book in ['Genesis','Mishnah_Avot']:
    txt_url = f'http://www.sefaria.org/api/texts/{book}.{section}'
    txt_response = requests.get(txt_url)
    txt_json = txt_response.json()
    sentences = txt_json['he']
    sentence = sentences[0].rstrip()
    print('------')
    print(book)
    print(sentence)
    print('last char -->',sentence[-1])
    print('last char encoded -->',sentence[-1].encode('UTF8'))
```
```
------
Genesis
<big>בְּ</big>רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃
last char --> ׃
last char encoded --> b'\xd7\x83'
------
Mishnah_Avot
משֶׁה קִבֵּל תּוֹרָה מִסִּינַי, וּמְסָרָהּ לִיהוֹשֻׁעַ, וִיהוֹשֻׁעַ לִזְקֵנִים, וּזְקֵנִים לִנְבִיאִים, וּנְבִיאִים מְסָרוּהָ לְאַנְשֵׁי כְנֶסֶת הַגְּדוֹלָה. הֵם אָמְרוּ שְׁלשָׁה דְבָרִים, הֱווּ מְתוּנִים בַּדִּין, וְהַעֲמִידוּ תַלְמִידִים הַרְבֵּה, וַעֲשׂוּ סְיָג לַתּוֹרָה:
last char --> :
last char encoded --> b':'
```

**Comment by yishairasowsky** [comment]
Well apparently it was not as simple as I thought, as one can see from this example:
```
import requests
section = 1
for book in ['Genesis','Mishnah_Avot']:
    txt_url = f'http://www.sefaria.org/api/texts/{book}.{section}'
    txt_response = requests.get(txt_url)
    txt_json = txt_response.json()
    sentences = txt_json['he']
    sentence = sentences[0].rstrip()
    print('------')
    print(book)
    print(sentence)
    sentence = sentence[:-1] + b'\xd7\x83'.decode('utf8')
    print('last char -->',sentence[-1])
    print('last char encoded -->',sentence[-1].encode('UTF8'))
```
```
------
Genesis
<big>בְּ</big>רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃
last char --> ׃
last char encoded --> b'\xd7\x83'
------
Mishnah_Avot
משֶׁה קִבֵּל תּוֹרָה מִסִּינַי, וּמְסָרָהּ לִיהוֹשֻׁעַ, וִיהוֹשֻׁעַ לִזְקֵנִים, וּזְקֵנִים לִנְבִיאִים, וּנְבִיאִים מְסָרוּהָ לְאַנְשֵׁי כְנֶסֶת הַגְּדוֹלָה. הֵם אָמְרוּ שְׁלשָׁה דְבָרִים, הֱווּ מְתוּנִים בַּדִּין, וְהַעֲמִידוּ תַלְמִידִים הַרְבֵּה, וַעֲשׂוּ סְיָג לַתּוֹרָה:
last char --> ׃
last char encoded --> b'\xd7\x83'
```

**Comment by rneiss** [comment]
The text is properly encoded. You may need to explicitly set the direction of the text you’re displaying: https://www.w3.org/International/questions/qa-html-dir

**Comment by yishairasowsky** [comment]
Thank you Russel so much for your reply and sending me that link!

*Yishai Rasowsky*
Mobile: (972) 54-848-2245
Home: (972) 54-751-6040
*Ask the Kollel <https://www.dafyomi.co.il/askollel.htm> | Jewish
Educational Broadcasting
<https://jewisheducationalbroadcasting.wordpress.com/>*
