### ISSUE TITLE
Difficulty scrolling in Hebrew texts

### ISSUE THREAD

**Issue by SaraWolkenfeld** [Sefaria/Sefaria-Project#117]
Reported by one of our partner institutions - scrolling is very uneven when going through Hebrew texts, often goes very slowly at first and then goes quickly and overshoots.

**Comment by jhasenklein** [comment]
Not only is it uneven but it is also very fast. Able to reproduce on Google Chrome on Yosemite and Win 8/10.

**Comment by blockspeiser** [comment]
I believe this is now fixed.
