### ISSUE TITLE
URL to address translation directly?

### ISSUE THREAD

**Issue by Chajmke** [Sefaria/Sefaria-Project#1172]
I coded a little plugin for Wordpress (to run on talmud.de). This asks the hebcal API for the recent Daf Yomi, displays it and links it to Sefaria. 

I thought, it would be smart for the German readers to go directly to a German translation. So the link my plugin creates is 

https://www.sefaria.org/Nedarim.54a?lang=bi&vside=Talmud_Bavli._German_trans._by_Lazarus_Goldschmidt,_1929_[de]%7Cen&utm_medium=api)

lang=bi that’s the display in two languages. And I thought, _vside_ would be sufficient to activate German. But it doesn’t work. So I guess, I am doing something wrong. Any hints?
This is not an error, but it seems, this detail is not part of the API documentation. (If yes, sorry)

**Comment by rneiss** [comment]
Hey Chajm,

The parameter you want is `ven` https://www.sefaria.org/Nedarim.54a?ven=Talmud_Bavli._German_trans._by_Lazarus_Goldschmidt,_1929_[de]&lang=bi
