### ISSUE TITLE
Link Explorer: Non standard behavior on IE

### ISSUE THREAD

**Issue by EliezerIsrael** [Sefaria/Sefaria-Project#121]
When links are hovered over, they are highlighted.  That's as should be.  
On IE, they remain highlighted, even after mouse-out.

**Comment by elyashiv** [comment]
On what versoins of IE do you get this behaviour?

**Comment by EliezerIsrael** [comment]
Good question.  I generally don't use IE.  Every time I did, I saw this issue.

**Comment by alis0nc** [comment]
I can reproduce this issue on Internet Explorer 10 on Windows 7. 

![sefaria 121 ie10](https://user-images.githubusercontent.com/4296609/29131276-629a6af6-7cfa-11e7-8916-4c53dd54e541.png)

**Comment by eykanal** [comment]
This does not seem to be an issue on IE11 (11.0.9600.18816). Can someone see whether this is still an issue?

**Comment by yishairasowsky** [comment]
is this still an issue? i could not reproduce it.

**Comment by blockspeiser** [comment]
I'm going to close this issue since we don't have any recent reports of the issue. Thanks.
