### ISSUE TITLE
Duplicate lines in Parshas Hamon

### ISSUE THREAD

**Issue by mattpolanieckidev** [Sefaria/Sefaria-Project#1231]
Why are there duplicate lines when requesting Parshas Hamon via API? Is it possible to filter for these?

http://www.sefaria.org/api/texts/Siddur_Sefard%2C_Various_Prayers_%26_Segulot%2C_Parashat_Haman_Reading_for_Tuesday_Beshalach.1

**Comment by HadaraRachel** [comment]
Hi, this seems to be an issue of shnaim mikra ve'echad targum, in which case the lines are duplicated intentionally.
There is another version [here](https://www.sefaria.org.il/Siddur_Sefard%2C_Additional_Prayers_%2C_Chapter_of_Manna?lang=he&with=all&lang2=he) or through Parashat Beshalach. 
if this is not the case, or for any other inquiry that has to do with content or bugs, please write to us at sefaria@hello.org
