### ISSUE TITLE
YouTube channel icon on user profile page links elsewhere 

### ISSUE THREAD

**Issue by rwp0** [Sefaria/Sefaria-Project#1285]
It seems like the code [trims](https://github.com/search?q=repo%3ASefaria%2FSefaria-Project%20youtube&type=code) YouTube URL into the channel ID or Youtube userhandle (`@USER`) which wrongly links to `https://www.sefaria.org/profile/CHANNEL_ID` when clicked on.
I couln't find the value for `{{ profile.youtube }}` template (not very familiar with Python).

The user page is accessed here:
https://www.sefaria.org/settings/profile

Supported YouTube channel URL's listed here:
https://support.google.com/youtube/answer/6180214?hl=en

And here's a screenshot I took describing this issue (the field is found in the "Contact" section):
![image](https://user-images.githubusercontent.com/68062695/224038515-aa7c63d7-4eac-4417-acbd-7809e3964644.png)

Clicking on the image below leads to an internal non-existent Sefaria page instead:
`https://www.sefaria.org/profile/UCHwauyydSuTO1b7aH9uNqjg`
[![image](https://user-images.githubusercontent.com/68062695/224039343-a76538da-37ee-4a3c-a721-32351a33bcd6.png)](https://www.sefaria.org/profile/UCHwauyydSuTO1b7aH9uNqjg)

**Comment by HadaraRachel** [comment]
thank you for reporting, we will look into this bug.
