### ISSUE TITLE
Text without html tags

### ISSUE THREAD

**Issue by ahuvia** [Sefaria/Sefaria-Project#1295]
i get text in hebrew with tag html.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/62541894/226474746-107cc35f-378e-40df-b61f-c4bf55c750ec.png">

what is it for?
how i down it?
how do i delete it?

**Comment by HadaraRachel** [comment]
Hi Ahuvia, we would be happy to help you out, please write to hello@sefaria.org for assistance.
