### ISSUE TITLE
Feature request: Display the Shas Bavli daf in Vilna edition layout

### ISSUE THREAD

**Issue by simong1080** [Sefaria/Sefaria-Project#1334]
What needs to happen so that users can view the daf as laid out in the Vilna edition of the Babylonian Talmud published by the widow and brothers Romm i.e. gemara in the middle, rashi on the inner margin, tosafot on the outer margin, and notations by the various other commentaries flanking both margins?

**Comment by HadaraRachel** [comment]
Hi Simon, 
Thank you. For future bugs or product feedback and requests please email hello@sefaria.org
