### ISSUE TITLE
Sefaria gets overwhelmed with queries for common words

### ISSUE THREAD

**Issue by Zacharymk1213** [Sefaria/Sefaria-Project#1364]
Over the years I've noticed that Sefaria starts glitching out when I search for a word that appears commonly like מצרים. A lot of the time the side-panel to narrow my search won't appear and things will just slow to a crawl. I don't think this happened when the database was smaller but given that Sefaria's database is ever-growing this should probably be addressed before it becomes a bigger problem.

**Comment by arubi9** [comment]
Hi there!

I’ve been observing a similar issue when searching for common terms like מצרים on Sefaria. It seems that the side-panel for refining the search doesn’t show up consistently, and the response time slows down significantly. This wasn’t much of an issue when the database was smaller, but as you mentioned, with Sefaria’s ever-expanding library, it’s becoming more pronounced.

It looks like a scalability challenge with the search function which may require optimizing the backend indexing or querying process. Addressing this now could help us avoid more significant performance bottlenecks in the future. I’m tagging this for the dev team to consider for their next sprint.

Thanks for flagging this up!

Best regards,
Avner Rubinov

**Comment by HadaraRachel** [comment]
Has this happened recently? 
If so, could you please send this bug report to hello@sefaria.org? 
Thanks for flagging
