### ISSUE TITLE
Looking for an engineer for a new project based on Sefaria

### ISSUE THREAD

**Issue by FlipTheWorldAgency** [Sefaria/Sefaria-Project#1366]
Hi, I am seeking an engineer to create a new Torah platform project integrating with the Sefaria library. The project is focused solely on digitizing the entire Breslev Literature, which comprises about 50 works in total, 4 generations of students, and about 12 authors. 

We have engineering PDF docs and Figma prototypes, and the complete branding is ready.

If you are serious and interested in working longterm to build this platform, please contact me.

Looking forward.

Best,
Yaniv

**Comment by EliezerIsrael** [comment]
Have you considered collaborating with Sefaria?  We'd be happy to host all of Breslev literature, connect it to the rest of Torah literature, help people find it...  Drop me a line - lev@.

**Comment by FlipTheWorldAgency** [comment]
Hi Lev, Thanks for your reply.

Yes I actually sent an email to Sefaria offering to collaborate but it seemed that they weren't interested.

Can I present you with the project? I have a keynote presentation.

Would love to explore that opportunity.

Thanks
Yaniv

On May 22, 2023 9:31 AM, Lev Eliezer Israel ***@***.***> wrote:

Have you considered collaborating with Sefaria? We'd be happy to host all of Breslev literature, connect it to the rest of Torah literature, help people find it... Drop me a line - ***@***.***
