### ISSUE TITLE
Sefaria Linkwr

### ISSUE THREAD

**Issue by goldbergmoshe** [Sefaria/Sefaria-Project#1385]
Hi,

I have started to utilise the the Sefaria Linker V3 on my website https://ontheparsha.co.za, however it is not coming up in webpages, how long does this take. Is this a bug on V3?

**Comment by HadaraRachel** [comment]
Hi Moshe, Thank you for reaching out. 
At this point Sefaria linker doesn't support PDFs, and if I am not mistaken that is what is loaded on your site?
please write to us at hello@sefaria.org for further assistance

**Comment by goldbergmoshe** [comment]
No, it's text.
