### ISSUE TITLE
How can I control which Torah translation is added to a sheet?

### ISSUE THREAD

**Issue by inklesspen** [Sefaria/Sefaria-Project#1421]
I have tried with both the old and the new source sheet editor. In both, I am having the same issue:

* If I add from the source sheet editor, I always get the Contemporary JPS translation. (It is a very good translation, but sometimes I want to use Everett Fox or the 1985 JPS.) I cannot see any option to control which translation is added.

* If I go into the Torah view, find the appropriate passage, change to the desired translation, and add it to the sheet from there, it gets added, but the verse numbers are missing, and I can't find any way to restore them in the editor.

**Comment by HadaraRachel** [comment]
Thank you, we are always working on improving the possibilities on Sefaria. 
Your request for this feature is recorded, is there are any further requests or suggestions please email hello@sefaria.org

**Comment by inklesspen** [comment]
Do… do you _not_ track needed improvements with github issues? I'm sure seeing a lot of them in the issue list.

**Comment by HadaraRachel** [comment]
In previous years we have tracked them on github, currently best to email us. 
Thank you!
