### ISSUE TITLE
extraneous markdown and text in Malachi 3:24

### ISSUE THREAD

**Issue by eyaler** [Sefaria/Sefaria-Project#1478]
in db.texts some versions e.g. Miqra According to Mesora, Tanach with Nikkud, Tanach with Text Only of Malachi 3:24 seem to have an extraneous
`
<br><small>[הנה אנכי שלח לכם את אליה הנביא לפני בוא יום יהוה הגדול והנורא]</small>`

**Comment by HadaraRachel** [comment]
Thank you @eyaler, we will correct this.
For future corrections such as these, please reach out to corrections@sefaria.org
