### ISSUE TITLE
API question: Vowel points and cantillation

### ISSUE THREAD

**Issue by shaze** [Sefaria/Sefaria-Project#1501]
Hello Sefaria Team

I hope this is the right place to ask the question -- is there a way of using the API to get the Hebrew text  of the Torah (a) with cantillation and vowel points and (b) without vowel points? Sorry this may be obvious, but using the example API call gives the Hebrew with the vowel points, which is great, but I'd also like to get the other versions.

Many thanks for your work

**Comment by rneiss** [comment]
Hey @shaze,

One way to do this is to explicitly ask for the specific version of the text you want by using the `vhe` parameter e.g.:
a: https://www.sefaria.org/api/texts/Genesis.1.1?context=0&commentary=0&vhe=Tanach%20with%20Ta%27amei%20Hamikra
b: https://www.sefaria.org/api/texts/Genesis.1.1?context=0&commentary=0&vhe=Tanach%20with%20Text%20Only

An alternate approach is to just request the former and to explicitly exclude the unicode range containing nikudot and taamim: e.g. in python: `regex.sub(r"[\u0591-\u05C7]", "", rawString)`

**Comment by shaze** [comment]
@rneiss Many thanks -- that's really helpful, and the API an amazing resource.
