### ISSUE TITLE
Enhancement for the name api

### ISSUE THREAD

**Issue by ykaner** [Sefaria/Sefaria-Project#1526]
## The issue
In order to open a book/ref in sefaria from the search bar I need to type the exact name of the book, or one of the names listed in `heTitleVariants` of this book. This make it very hard and confusing, relatively to the Responsa project (פרויקט השות). 
## The solution
The simples way to make it easier for users to open the book/ref they want is by extending the `heTitleVariants` and including there the most useful names and nicknames of the books. 
For example if I want to open `רמבם הלכות דעות`, I must type one of the following names:
```
  "heTitleVariants": [
    "רמב\"ם, הלכות דעות",
    "משנה תורה, הל' דעות",
    "רמב\"ם, הל' דעות",
    "רמב\"ם הלכות דעות",
    "רמב\"ם הל' דעות",
    "רמב״ם, הלכות דעות",
    "רמב”ם, הלכות דעות",
    "רמב״ם, הל' דעות",
    "רמב”ם, הל' דעות",
    "רמב״ם הלכות דעות",
    "רמב”ם הלכות דעות",
    "רמב״ם הל' דעות",
    "רמב”ם הל' דעות",
    "משנה תורה, הלכות דעות"
  ],
```

In Responsa (פרויקט השות) I can type just `רמבם דעות` (and many other useful options) which make it much more intuitive for users. 
So I suggest extending the   `heTitleVariants` for the most useful books and names.  
I hope this will not cost too much in time, but will greatly help users. 

## The implementation
I have applied some heuristics on the titles. Tell me where/how to update it in sefaria's db.

**Comment by rneiss** [comment]
Hey Yosef,

If I understand this issue correctly you're not asking for any specific code changes or new features, but rather simply that we include more title variants for various works. Is that correct?

Best, 
Russel

**Comment by ykaner** [comment]
Yes, and I have some changes, I'm just not sure how to submit them.

**Comment by rneiss** [comment]
Hey Yosef, 

Again, thanks for these feedback. I think I'm going to close the issue right now b/c we're probably not going to change the underlying API behavior, but we would love the various alt-titles you have so we can solve this issue on the data end and give the user the experience that you're articulating. 

Can you send them to hello@sefaria.org?

Thanks so much!
