### ISSUE TITLE
[bug]Sefria doesn't track my previous page when using collections 

### ISSUE THREAD

**Issue by ilan-pinto** [Sefaria/Sefaria-Project#1547]
## how to reproduce
1.enter to s collections like (hok le Israel) https://www.sefaria.org.il/collections/%D7%97%D7%A7-%D7%9C%D7%99%D7%A9%D7%A8%D7%90%D7%9C?tab=sheets 

![image](https://github.com/Sefaria/Sefaria-Project/assets/57443637/2ffdac0a-ebae-460e-9d48-45098536e9c8)

2. pick a day 
3. click back 

### expected 
expected to go back to the tab=sheets of the parashah that was picked earlier 

### what happens 
routed to a general page with all the parashot 

![image](https://github.com/Sefaria/Sefaria-Project/assets/57443637/f6957c5a-bd25-44ff-808f-694dbb0f2591)

**Comment by HadaraRachel** [comment]
Thanks for reaching out Ilan, we will look into this.
For future bugs or product feedback please write to hello@sefaria.org

**Comment by ilan-pinto** [comment]
@HadaraRachel, where do you manage all the bugs? 
how can i contribute ?

**Comment by HadaraRachel** [comment]
We manage them in-house so that they can be triaged and treated accordingly. 
Happy to follow up about contributing via email if you are interested hadara@sefaria.org
