### ISSUE TITLE
[feature] custom layouts 

### ISSUE THREAD

**Issue by ilan-pinto** [Sefaria/Sefaria-Project#1548]
## requirement 
add the ability to text in parallel in a way that the main text and the Mefrashim can be seen together 
but in a custom way in which each user can pick the X Mefarshim to see. 
the Mefarshim data will change according to the main data the user scrolls the 

## how
for example, a user can pick a Parasha and 2 midrashim (Rashi and a midrash) at the middle will see the Parasha, and on the left Rashi on the right the Midrash.  
that can be done with many other texts

**Comment by HadaraRachel** [comment]
Thanks for suggesting Ilan
We will look into it, for further bugs, product feedback and feature requests please write to hello@sefaria.org
