### ISSUE TITLE
 high security vulnerabilities  

### ISSUE THREAD

**Issue by ilan-pinto** [Sefaria/Sefaria-Project#1549]
The following packages have vulnerabilities. 

bleach==1.4.2
django-debug-toolbar==2.2 
html5lib==0.9999999
httplib2==0.18.1
lxml==4.6.1
ua-parser==0.10.0

**Comment by edamboritz** [comment]
Hi, thank you so much for writing to us about this! 
We are already working on a general upgrade path for all of our dependencies, and will be sure to be looking into these at the top of that list.
