### ISSUE TITLE
Easier Ways to Access Parshot

### ISSUE THREAD

**Issue by SamGreenwood1** [Sefaria/Sefaria-Project#1588]
It would be nice if you could bookmark full parshot and also if there was an easier way to get straight to the parssah you want to read like assigning each a unique URL.

**Comment by rneiss** [comment]
Hey Sam,

It's undocumented, and it immediately redirects to a more standardized url, but our system understands url refs to parshiyot.

e.g.: https://www.sefaria.org/Miketz or https://www.sefaria.org/V'Zot%20HaBerachah or https://www.sefaria.org/וישלח
