### ISSUE TITLE
Sefaria.Js Now Requires React?

### ISSUE THREAD

**Issue by krixano** [Sefaria/Sefaria-Project#1693]
I can no longer use [sefaria.js](https://github.com/Sefaria/Sefaria-Project/wiki/Sefaria.js) because it seems to require React. I don't need React, so I don't see why sefaria.js should need it either if people are just using the API.

**Comment by edamboritz** [comment]
Hi! 
Thanks for letting us know. We will look into this. 
We do use React extensively in Sefaria's UI so cant be entirely sure when a dependency crept in to the js module you're using, or if it can be untangled, but we're investigating.

**Comment by edamboritz** [comment]
We believe this is now fixed!

**Comment by krixano** [comment]
@edamboritz Thanks!
