### ISSUE TITLE
cannot search

### ISSUE THREAD

**Issue by yishairasowsky** [Sefaria/Sefaria-Project#1708]
sorry to bother you! but i cannot search using the regular method (first image) 
<img width="952" alt="image" src="https://github.com/Sefaria/Sefaria-Project/assets/39579959/d08d9c85-98de-4cc1-a0b3-b0847469a4d7">
but i can search using the torah tab method (second image)
<img width="939" alt="image" src="https://github.com/Sefaria/Sefaria-Project/assets/39579959/8924ae6d-ada1-442c-9a92-af83f7a23ae7">

**Comment by EliezerIsrael** [comment]
Thanks for the error report @yishairasowsky.  You alerted us to a botched merge, and we fixed it in https://github.com/Sefaria/Sefaria-Project/commit/e2d087ddbc20f46a03224dcd06b44e726b6be8b3

**Comment by EliezerIsrael** [comment]
Interestingly, there are 12 search results for "[trapezoid](https://www.sefaria.org/search?q=trapezoid&tab=text&tvar=1&tsort=relevance&svar=1&ssort=relevance)".

**Comment by yishairasowsky** [comment]
thanks Lev you are the best
