### ISSUE TITLE
A user is able to follow themselves

### ISSUE THREAD

**Issue by yfram** [Sefaria/Sefaria-Project#1714]
If a user views the people folloed by someone following them, they are able to follow themselves. They then show up in their own "followed by" list.
<img width="419" alt="image" src="https://github.com/Sefaria/Sefaria-Project/assets/57146295/568e8da4-9666-4be9-889c-a22246a4a41e">

**Comment by HadaraRachel** [comment]
Thank you Yoni for reporting this, we will look into it.
for future bug reports please reach out to us through hello@sefaria.org
