### ISSUE TITLE
Version selecting in /api/bulktext isn't working

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#1724]
The following endpoints work using the `/api/texts` endpoint:
* [api/texts/Mishnah_Berakhot.2](https://www.sefaria.org/api/texts/Mishnah_Berakhot.2)
* [api/texts/Mishnah_Berakhot.2?ven=Open_Mishnah](https://www.sefaria.org/api/texts/Mishnah_Berakhot.2ven=Open_Mishnah)

But when I try do to the same using the `/api/bulktext` endpoint, which we added support in #1388, I can't get it to work

* [/api/bulktext/Mishnah_Berakhot.2?useTextFamily=1](https://www.sefaria.org/api/bulktext/Mishnah_Berakhot.2?useTextFamily=1)
  *  Works fine
* [api/bulktext/Mishnah_Berakhot.2?useTextFamily=1&ven=Open_Mishnah](https://www.sefaria.org/api/bulktext/Mishnah_Berakhot.2?useTextFamily=1&ven=Open_Mishnah)
  * Returns an empty English array
* [https://www.sefaria.org/api/bulktext/Mishnah_Berakhot.2?ven=Open_Mishnah](api/bulktext/Mishnah_Berakhot.2?ven=Open_Mishnah)
  * Returns `{"Mishnah_Berakhot.2": {"error": 1}}`

I've tried to emulate the code this calls in the `./cli` script and it's working locally for me. So not sure what's going on, unless perhaps my data dump is old.

**Comment by nsantacruz** [comment]
@ronshapiro It seems we're using a different convention for formatting the version title for `bulktext`. E.g. this URL works https://www.sefaria.org/api/bulktext/Mishnah_Berakhot.2?useTextFamily=1&ven=Open%20Mishnah (note the URL-encoded space in the version title name as opposed to an underscore).

**Comment by nsantacruz** [comment]
Ideally we should use the same formatting as in other places. We don't have standardized code that deals with this, but would be happy for a PR that would allow for the same version title formatting in bulktext.

Closing this issue for now.
