### ISSUE TITLE
HOW TO GET ALL OF THE MISHANSH NAME ORDER BY SEDER?

### ISSUE THREAD

**Issue by eliyahu-kriel** [Sefaria/Sefaria-Project#1753]
HI THANKS FOR THIS GREAT API!
I WANT TO GET ALL OF THE MISHNAS NAMES ORDER OR GROUPED BY THERE SEDER?
I WALKED THRUE THE API AND DIDINT ABLE TO DO IT
THANKS

**Comment by nsantacruz** [comment]
Hi! Thanks for the question. You can use the [Index API](https://github.com/Sefaria/Sefaria-Project/wiki/API-Documentation#get-apiindex) which returns our full table of contents as a tree in JSON. Traverse the tree to find all of the books of Mishnah under the "Mishnah" category. They will be in the order of Mishnah and grouped by Seder.

**Comment by eliyahu-kriel** [comment]
hi thanks for responding

still not understand, there is no example of url and entities in the docs

i tried :

`https://www.sefaria.org/api/v2/index/Mishnah`

returns
`{
    "error": "No book named 'Mishnah'."
}`

can you give me the url ?

**Comment by eliyahu-kriel** [comment]
also tried

`https://www.sefaria.org/api/index/titles/mishnah`

and get same error

`
{
    "error": "No book named 'Titles/mishnah'."
}
`

**Comment by EliezerIsrael** [comment]
What @nsantacruz writes would work - getting the full table of contents and pulling out Mishnah.
But for this case, I think the shape API is better suited.  
Try - https://www.sefaria.org/api/shape/Mishnah
