### ISSUE TITLE
Linker 3 isnt working at all

### ISSUE THREAD

**Issue by staycreativedesign** [Sefaria/Sefaria-Project#1786]
```
 <p class="torah">Genesis 1:1</p>
<script type="text/javascript" charset="utf-8" src="https://www.sefaria.org/linker.v3.js"></script>
  <script>
    sefaria.link({
      whitelistSelector: ".torah",
    });
  </script>
</body>
```

Produces:

I've also added the example in the docs but nothing still shows up.

<img width="551" alt="Screenshot 2024-01-24 at 9 49 58 PM" src="https://github.com/Sefaria/Sefaria-Project/assets/1952722/19cd10fd-54a9-4bed-9d87-3c09a69dd451">

Not only that , it when trying to select the corpus it also doesnt work.

**Comment by nsantacruz** [comment]
Thank you for the bug report. I pushed a fix to production. Note, your example may be cached so it's worthwhile to try another example.
