### ISSUE TITLE
Linker 3 Corpus selection not working

### ISSUE THREAD

**Issue by staycreativedesign** [Sefaria/Sefaria-Project#1789]
```
    <script type="text/javascript" charset="utf-8" src="https://www.sefaria.org/linker.v3.js"></script>
    <script>
      sefaria.link({
        whitelistSelector: ".torah",
        versionPreferencesByCorpus: {
          Tanakh: {
            en: "The Koren Jerusalem Bible"
          },
        },
      });
    </script>
```

the link works but the tanakh version goes to The Contemporary Torah, JPS, 2006

Instead of selected Tanakh corpus

**Comment by nsantacruz** [comment]
I'm seeing this with the snippet of code above which is displaying the Koren text. What is the issue you're seeing?

<img width="514" alt="Screenshot 2024-01-29 at 10 49 02" src="https://github.com/Sefaria/Sefaria-Project/assets/6697474/696c7061-55b1-4c37-987e-2afc672fcd75">

**Comment by staycreativedesign** [comment]
works now I guess cache? thank you!
