### ISSUE TITLE
Local install on Windows failed for Python 3.7

### ISSUE THREAD

**Issue by Stoops-ML** [Sefaria/Sefaria-Project#1795]
The setup instructions recommend installing Python 3.7 (see [here](https://github.com/Sefaria/Sefaria-Project?tab=readme-ov-file#1-install-python-37)), however I was unable to complete the installation due to an incompatibility with Pillow (version 10.0.1). Note that I am using a Windows machine.

Using Python 3.8 successfully installed all the requirements. I haven't tried with later versions.

Is the Python 3.7 still the recommended version, or do setup instructions need updating?

**Comment by edamboritz** [comment]
Hi! Thanks for reaching out. 
The setup instructions do indeed require some tweaking, something we are already in the process of. 
For now Python 3.8 or 3.9 should work as a baseline.

**Comment by Stoops-ML** [comment]
Is there a branch where this work is being done? I'm happy to contribute.
