### ISSUE TITLE
Download Source Sheets

### ISSUE THREAD

**Issue by rivkahcarl** [Sefaria/Sefaria-Project#181]
It would be great to have the ability to download a source sheet once complete and save perhaps to something like a pdf. Often there is a need to save to ones computer prior to printing and a need for access to the sheet without internet service.

**Comment by blockspeiser** [comment]
It is possible to save source sheets as PDFs, albeit a little indirectly. You can use the "Save to PDF" option from the Print menu, built into your browser (it appears slightly differently in each browser and OS).

**Comment by rivkahcarl** [comment]
oh I see what you mean. 
Definitely not as intuitive, but feel free to close.
