### ISSUE TITLE
hebrew font in linux chrome (Version 47.0.2526.106)

### ISSUE THREAD

**Issue by highflux7** [Sefaria/Sefaria-Project#183]
The hebrew displayed using the Chrome browser v47.0.2526.106 has superfluous 'boxes' all throughout the text.  Not a problem w/Firefox.

![screenshot from 2015-12-16 01 38 41](https://cloud.githubusercontent.com/assets/6489370/11835484/841a452a-a399-11e5-959b-63d9840d49e1.png)

**Comment by ephraim-sefaria** [comment]
Hi,
Chrome does indeed seem to have an issue with some unicode characters in it's default font set. 
The boxes seem to be markers for where the cantillation marks are in the text. 
Depending on your Linux distribution, there are a few things you can try. 
On Ubuntu you can first try (if you have not already) updating to the latest chrome version. 
That will probably not have a big effect. 
Try installing the Microsoft font pact: ttf-mscorefonts-installer it should be available via apt-get. Though you may need to pay attention that it installed correctly, 
After that try deleting any extra config files in ~/.config/fontconfig or your font config location. 
Then try forcing a rebuild of the font cache 'sudo fc-cache -f -v'

**Comment by highflux7** [comment]
Thanks!

Indeed using ubuntu (14.04.3) with all the updates.  Tried your most detailed suggestions to no avail.  Guess I'll stick with Firefox until Chrome fixes their font support or something else can be figured out.
Thanks again for your prompt and detailed response.

**Comment by blockspeiser** [comment]
Since we've started embedding our own fonts in the Web app, I believe these problem should be fixed on Linux. Let us know if not, thanks.
