### ISSUE TITLE
Links in "Connections between Talmud and Tanach" don't work

### ISSUE THREAD

**Issue by TomWeisz** [Sefaria/Sefaria-Project#187]
Nothing happens when I click on the bubble saying click here.  I tried it in Chrome and IE.  Is this a known bug?

**Comment by EliezerIsrael** [comment]
@TomWeisz Thanks for the report.  Can you tell me what OS and browser versions you're seeing this behavior in?

**Comment by TomWeisz** [comment]
Thank you so much for the quick response. I am using Windows 10 and I.
By the way I love what you are doing. It is a great tool

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Dec 30, 2015 at 11:56 AM -0800, "Lev Eliezer Israel" <notifications@github.com<mailto:notifications@github.com>> wrote:


@TomWeisz<https://github.com/TomWeisz> Thanks for the report. Can you tell me what OS and browser versions you're seeing this behavior in?

-

**Comment by rneiss** [comment]
I can replicate. It appears in both ie11 and Edge as well.

I'll dig into it.

**Comment by TomWeisz** [comment]
Let me push my luck in finding such responsiveness.
Would it be possible to get a listing of the all the links over some range, e.g. one Chapter?
The graphic is very nice and gives you ideas but then to dig deeper the list would save time.
I know – you’ll put it on the development list which I am sure is miles long.

**Comment by EliezerIsrael** [comment]
@TomWeisz We have something close, but not perfect.  From the API you can request all of the links for any chapter or verse.  For example, if you request http://www.sefaria.org/api/links/Exodus.10, you'll get all of the links to Exodus 10, with metadata and text.  http://www.sefaria.org/api/links/Exodus.10.12-14 would do the same just for verses 12-14.   It's in a technical format (JSON), but the info is there.

**Comment by TomWeisz** [comment]
Wow, great.
Pushing further.  Is there a way to search/edit the file so that I can find the sources quicker.
I am not familiar with Json.  I just downloaded the viewer but I can’t find how to search the file
BTW – if it is not a secret, where are you guys?  I am in Netanya

**Comment by EliezerIsrael** [comment]
@TomWeisz We have people working in a bunch of locations. I'm in Jerusalem, with a few other members of the team.  We generally are working from the National Library.  

(We can take this conversation off of Github - I'm at lev@sefaria.org.)

**Comment by TomWeisz** [comment]
Thanks that's great . How about my question on searching in Jason files see below


Sent from Outlook Mobile<https://aka.ms/sdimjr>




On Wed, Dec 30, 2015 at 11:50 PM -0800, "Lev Eliezer Israel" <notifications@github.com<mailto:notifications@github.com>> wrote:


@TomWeisz<https://github.com/TomWeisz> We have people working in a bunch of locations. I'm in Jerusalem, with a few other members of the team. We generally are working from the National Library.

(We can take this conversation off of Github - I'm at lev@sefaria.org<mailto:lev@sefaria.org>.)

-

**Comment by rneiss** [comment]
re: the initial issue. It seems as if IE doesn't handle inline links in SVG in the expected way. There doesn't appear to be an easy workaround for it at this juncture, so we've put up a warning about the unexpected behavior, and hope that as development on IE 11/Edge continues they'll handle SVGs like Apple, Mozilla, & Google have.
