### ISSUE TITLE
Commentary pops up on Chrome for Android at the end of chapter

### ISSUE THREAD

**Issue by mmhoch** [Sefaria/Sefaria-Project#191]
When scrolling through a text,  at the end of a chapter, sefaria automatically loads the next chapter
If you have previously opened a commentary on the text and have closed it, when coming to the next chapter, the last commentary is opened again and the text moves back to the line of that commentary.

Way to reproduce:
- open a text, not being a last chapter
- open a commentary
- close the commentary
- scroll to the end of the chapter

**Comment by blockspeiser** [comment]
I believe this is fixed. I went through these steps to reproduce and nothing seems amiss. Let us know if we're missing something. thanks.
