### ISSUE TITLE
feat: Line endings for talmud bavli

### ISSUE THREAD

**Issue by dickermoshe** [Sefaria/Sefaria-Project#1922]
I'm working on a project where I'll be rendering the talmud as it appears printed.
To keep the original layout, I've gotten the line endings for each line of gemara, rashi and tosafot.
Would you be interested in a PR that would add this?

**Comment by EliezerIsrael** [comment]
@dickermoshe Yes!  That sounds like an amazing dataset.  Now where to put it...  It's either here or https://github.com/Sefaria/Sefaria-Data.  @edamboritz do you have an opinion on this one?

**Comment by dickermoshe** [comment]
I've run into an issue.
It seems you bavli has changed roshei tevos into full text א"כ >  אם כן.
Is there a version without this?

**Comment by saengel** [comment]
Hi @dickermoshe - we appreciate you reaching out. I'm curious to understand a bit better - let's continue this conversation. Is it possible to reach to us at developers@sefaria.org? Currently, we try to reserve our GitHub issues for problems within the code. Thanks!

**Comment by saengel** [comment]
Hi @dickermoshe - 
Thank you for the offer! Can we continue the conversation at developers@sefaria.org? I'll look into this and pick up there once I hear from you. Thanks!
