### ISSUE TITLE
Can we *please* use regular html rather than Javascript?

### ISSUE THREAD

**Issue by opengemara** [Sefaria/Sefaria-Project#194]
I'm having a few issues caused by the javascript behind Sefaria:

1. Go to [Sotah 17a](http://www.sefaria.org/Sotah.17a) and click on the Shittah Mekubetzes 3. You'll get into an infinite loop.
2. Speaking about clicking, why can't I open it in a new tab? If "Open Shitah Mekubetzes" would be a normal link, I would just middle click on it. Now I can't. 
  
  It gets quite  frustrating when I have to go back and forth between the Gemara and sources, and would make learning much more efficient if I could just open them in a new browser tab or window

**Comment by benschenker** [comment]
I can replicate this with Chromium 51.0.2683.0 (64-bit) and Chrome 49.0.2623.110 (64-bit) on OSX 10.10.5
The page flickers and the url switches between:
`http://www.sefaria.org/Shita_Mekubetzet_on_Sotah.17a?lang=he&layout=lines&sidebarLang=all`
and:
`http://www.sefaria.org/Shita_Mekubetzet_on_Sotah.17a.3?lang=he&layout=lines&sidebarLang=all`
A refresh seems to stop the flickering

**Comment by rneiss** [comment]
This should no longer be an issue in the new version of the website.
