### ISSUE TITLE
Can I use the `replaceDivineNames` function in MIT Licensed code?

### ISSUE THREAD

**Issue by SZRabinowitz** [Sefaria/Sefaria-Project#1983]
I am interested in implementing [this function](https://github.com/Sefaria/Sefaria-Project/blob/e4446cccffc74d936150f337248429a56b47a5a8/static/js/Editor.jsx#L337) function in an open sourced, MIT Licensed project. Specifically, I want permission to use the regexes on a more permissive license. Is this possible?

Thanks!

**Comment by nsantacruz** [comment]
Based on the below ([source](https://www.gnu.org/licenses/gpl-3.0.html))

> 5. Conveying Modified Source Versions.

You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:

    a) The work must carry prominent notices stating that you modified it, and giving a relevant date.
    b) The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.
    c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
    d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.

You need to apply GPT v3 to your code. That being said, we are not able to offer specific legal advice. I hope this helps.

**Comment by Shem0yosef** [comment]
Hoje
