### ISSUE TITLE
Scrolling Speed on Commentaries

### ISSUE THREAD

**Issue by jhasenklein** [Sefaria/Sefaria-Project#209]
Scrolling on the right sidebar with commentaries is very fast. When I begin to scroll, it starts at the top and I have to find my place again. Hard to stop on the exact place that I want. Was able to produce on Macbook/Macbook Air running OSX Yosemite and Windows 8/10 in Google Chrome. Similar issues in Firefox. Works better in Safari but not great.

**Comment by blockspeiser** [comment]
Hi there, 

Thanks for the report. We're getting very close to releasing a completely rebuilt front-end that addresses this and many other issues we've wanting to fix for a long time. If you want test out the new site in progress you can take a look at www.sefaria.org/s2.

thanks

**Comment by jhasenklein** [comment]
This looks great. Is there a place for feedback? I plan on sharing with my
full class. Also, what is the ETA of the full release?

Jared Hasen-Klein
jhasenklein@gmail.com / jhasen-klein669@milkenschool.org
(818) 439-2892

On Wed, May 4, 2016 at 10:36 AM, Brett Lockspeiser <notifications@github.com

**Comment by blockspeiser** [comment]
We'll be launching in June. There's a red button in the header that leads to an email address where you can send us feedback. This is not publicly launched yet, so please don't share publicly yet (I'm assuming not too many people read the comments of our GitHub issues :) ). If you want to share with a class that is great -- we have a number of classrooms currently beta testing the new site. You can get in touch Sara our director of Education if you'd like to talk about ways to use the site in the classroom or to have more 1:1 feedback discussion. thanks!

https://github.com/Sefaria/Sefaria-Project/wiki/Sefaria-for-Educators
