### ISSUE TITLE
feat: copying on ios

### ISSUE THREAD

**Issue by moshetanzer** [Sefaria/Sefaria-Project#2090]
Hi, 

Have reported this before, wasnt able to find issue now - since the introduction of the dictionary (that you can hold and get refrences from jastrow) it has become extrmely painful to copy simple text - you first have to click the portion let sefaria botoom sheet open, click share, find copy - then you have an entire paragrapht that you have to start choppping.

I think there are many people like myself who rarely use the dictionary - so even if we can find a way to enable both (though i think with touch start and a bit of fidling may be possible) - there should be a way to disable the dicitoanrly so copying can be used by simply selectin the text you need!

**Comment by saengel** [comment]
Hi @moshetanzer - thank you for reaching out, and for the feedback. I'm sorry you've run into this issue. 
As I wrote on the previous issue, please send feature requests to [hello@sefaria.org](mailto:hello@sefaria.org)

Thanks!
