### ISSUE TITLE
feat: no Seif Katan in reference in Shulchan Aruch

### ISSUE THREAD

**Issue by moshetanzer** [Sefaria/Sefaria-Project#2091]
Hi,

When using sefaria as a reference - it is a total pain that there is no seif katan in the shulchan aruch.

reprouction:
1. go to shulchan aruch
2. click on a portion
3. click one of the mefarshim
it now only shows the text without the seif katan or "ois" - to view the ois you have to open it and see and then come back (due to not being able to open numerous sefarim in same screen see issue https://github.com/Sefaria/Sefaria-Project/issues/2089)

suggestion would be to show the Seif Katan - my sepcific use case was the Taz

**Comment by saengel** [comment]
Hi @moshetanzer - thank you so much for the feedback and the step-by-step walkthrough to reproduce. 

This is another good one to direct to hello@sefaria.org. Thanks for the understanding!
