### ISSUE TITLE
Feature Request: Ability to view all commentaries on one verse

### ISSUE THREAD

**Issue by jhasenklein** [Sefaria/Sefaria-Project#210]
I would like to be able to click on a verse and see all of the applicable commentaries. Right now, I can see all of the commentaries on one chapter only. I would like to have a similar interface as when you double click on one commentary and view it in the full screen format -- but for all of the commentaries on one specific verse entirely.

**Comment by blockspeiser** [comment]
If I'm understanding you correctly, this is now possible with the new site. In the sidebar click "COMMENTARY" to load all the comments for one line. Give it a spin and if you issue is still not addressed please give another shot at filling in the details of what exactly you'd like to see.
