### ISSUE TITLE
`api/find-refs/` endpoint returns 500 error when invalid text object is passed in

### ISSUE THREAD

**Issue by matanyall** [Sefaria/Sefaria-Project#2126]
Working on integrating the find-refs api into my project, and I've noticed that if you have an invalid `text` object, you get a 500 and an HTML response, rather than something like a 400 Bad Request.

```json
{
  "text": {
    "body": "Genesis 1:1 is a citation and also Mishnah Peah 3-4. So is שמות ב",
    "title": "sfsd" // if either of these are missig
  },
  "lang": "he"
}
```
How to replicate:
Just click the "try it" button without setting any values on the [docs site](https://developers.sefaria.org/reference/post_api-find-refs)

I think this can be fixed by adding validation logic in `sefaria/helper/linker.py`:

```python
def _unpack_find_refs_request(request):
    post_body = json.loads(request.body) # either validate here
    meta_data = post_body.get('metaDataForTracking')
    return _create_find_refs_text(post_body), _create_find_refs_options(request.GET, post_body), meta_data


def _create_find_refs_text(post_body) -> _FindRefsText:
    from sefaria.utils.hebrew import is_mostly_hebrew
    title = post_body['text']['title'] # this is what is probably throwing the exception, and catching it here and raising and InputError or something would make it work
    body = post_body['text']['body']
    lang = post_body['lang'] if 'lang' in post_body else 'he' if is_mostly_hebrew(body) else 'en'
    return _FindRefsText(title, body, lang)
```

**Comment by saengel** [comment]
Hi @matanyall - this is great feedback. Thank you!
Our engineering team has a PR to fix (see https://github.com/Sefaria/Sefaria-Project/pull/2129) which is undergoing review now. 
Once again, much appreciated!
