### ISSUE TITLE
High Speed - Low Latency Web Server for a better experience

### ISSUE THREAD

**Issue by henry-hz** [Sefaria/Sefaria-Project#213]
Many thanks for the project, amazing!
Let me suggest to move to Cowboy server [Elixir/Erlang],
http://www.phoenixframework.org/

Take a look, using websockets, how fast it goes:
https://github.com/bigardone/phoenix-trello

**Comment by unforgettableid** [comment]
Dear Mr. Hazan,

Sefaria is written in Python.

You are suggesting that the Sefaria team rewrite the entire website in Erlang, correct?

P.S.  Thank you for the compliment!

**Comment by henry-hz** [comment]
If you want to integrate real-time communications (e.g. click and chat inside a specific Rahsi, more than 500.000 users per server), it should be ported. Porting to have a better latency response would be too much.

**Comment by EliezerIsrael** [comment]
When we approach such issues of scale, we'll consider it.
