### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by opengemara** [Sefaria/Sefaria-Project#225]
In the old website, one could see the source of the text, as well as change the translation. I don't see this button on the new website.

**Comment by rneiss** [comment]
You can access this information/functionality by clicking the title of the text in the top menu bar:

![1](https://cloud.githubusercontent.com/assets/1596539/16100246/9e07f824-3322-11e6-9e49-82034dbfb8bd.png)
![2](https://cloud.githubusercontent.com/assets/1596539/16100245/9dea918a-3322-11e6-8aaf-050c37adaf7e.png)
