### ISSUE TITLE
Upload Photo to Source Sheets

### ISSUE THREAD

**Issue by rivkahcarl** [Sefaria/Sefaria-Project#233]
Uploading photo from local file system to source sheet. 

I was interested in pasting an image from my file system and add it to a source sheet. I noticed one can only paste from a URL, Youtube video or MP3.

It would be great to be able to upload a photo locally.
If there is a way to do this already, feel free to close issue.

**Comment by rneiss** [comment]
There is no way yet to do this, though it's a feature we do hope to build out eventually.

In the interim we suggest uploading an image via https://imgur.com and pasting the direct link into the media box.

**Comment by pzp1997** [comment]
@rivkahcarl You can now do this as of about noon today! Hope you find this feature useful. 
Shabbat shalom from New York!
\- Palmer

**Comment by rivkahcarl** [comment]
Thanks @pzp1997 for this addition! Extremely helpful, will try to test this out soon.
