### ISSUE TITLE
Reusable Widget for Selecting Text by interactive Typing

### ISSUE THREAD

**Issue by blockspeiser** [Sefaria/Sefaria-Project#24]
The experience in of adding a new source has a first approximation of this, but it's not very clean, reusable or reliable. What's needed:
- A text area for typing citations
- Suggestions for texts titles
- Feedback for the next info need to complete a valid citation ("Enter a chapter")
- When the citation narrow enough, showing the text the actual text and making it easy to choose a selection visually. (e.g., once I've type Yoma 12b, I should see the full text f the daf and then be able to select the correct line numbers)

**Comment by erg0sum** [comment]
@blockspeiser Hi, I'm a dev living in Chicago, If you point me at the code, I could take a look and see if I can refactor and generalize it.

**Comment by blockspeiser** [comment]
Hey @erg0sum sorry I've lost track of this comment. The code that's doing this mostly lives in the function checkRef() in utils.js (https://github.com/Sefaria/Sefaria-Project/blob/master/static/js/util.js#L1497). 

It currently it used in two contexts: 1) the add to source sheet modal in the source sheet building and 2) the add source modal in the reader app. This code is coupled to them in ways. 

The basic idea is to build up a list of test to run in a particular sequence. The test matches a regular expression against the input. Each test has an action associated with it. The first test that matches runs its action.

The actions may be something like prompting the user for more input with a particular message or getting data from the API so we know more about what the user is asking for.

**Comment by yishairasowsky** [comment]
@erg0sum did you find success refactoring? i would like to help if possible.

**Comment by EliezerIsrael** [comment]
I think we can call this closed, given the current implementation.
