### ISSUE TITLE
Questions about the Sefaria Auto-Linker and GitHub

### ISSUE THREAD

**Issue by unforgettableid** [Sefaria/Sefaria-Project#249]
Hi!  I have some questions about the [Sefaria Auto-Linker](http://www.sefaria.org/linker) (aka the Sefaria Linker) (aka the Sefaria Auto-Linking Bookmarklet).

A) How many people wrote it?

B) Is a copy already somewhere on GitHub?

C) If not: Might the author(s) be willing to please release it as GPL open-source software?

Kol tuv!

cc:  @EliezerIsrael

**Comment by rneiss** [comment]
The code the bookmarklet injects can be found here: https://github.com/Sefaria/Sefaria-Project/blob/2e659fa97f84512fd6e0de69e4ba75003b8eb78a/templates/js/linker.js

It is part of the Sefaria Project and therefore released under the same GPL license as the rest of the code.

**Comment by unforgettableid** [comment]
Ah OK.

I had used GitHub to search for [`[ linker.js ]`](https://github.com/Sefaria/Sefaria-Project/search?utf8=%E2%9C%93&q=linker.js) but this query didn't find `linker.js` at all.

In retrospect, I should have searched for [`[ filename:linker.js ]`](https://github.com/Sefaria/Sefaria-Project/search?utf8=%E2%9C%93&q=filename%3Alinker.js) instead.  The latter query finds the file instantly.

My mistake.  Thank you for pointing me in the right direction.  Also, I thank you all for maintaining Sefaria!
