### ISSUE TITLE
Section Headers in Source Sheets

### ISSUE THREAD

**Issue by pzp1997** [Sefaria/Sefaria-Project#252]
I went to a shiur last week and was pleased to discover that the speaker used Sefaria to create his source sheet handouts. I went up to him after the shiur and asked him what he thought of Sefaria and if there were any features that he thought we were missing. He quickly replied that he wished he could add titles to his sources or in some way add titles to his source sheet to divide it up into distinct sections.

Ultimately, he used comments for this purpose, but he felt like he was misusing that feature by doing so. I agree with him that using a comment to denote section headers feels semantically incorrect. Furthermore, when viewing a source sheet on Sefaria, a little chat bubble icon is displayed in the left margin of a comment. This makes perfect sense for a normal comment but looks rather strange when the comment is meant to be a title. (Note that this is not a problem when printing the sheet or exporting the sheet to Google Drive, as the chat bubble is not shown in those representations.)

I see a few potential solutions to this issue. We could...

- add an optional title field to all sources, but I don't believe that this really solves the problem and it would create many more problems in the process.
- rename "comments" to something that is more general and encompasses all of the possible use cases of a comment, i.e. as an author's comment on a source (that is the true intended purpose of a comment, right?), as a section header, etc. Two downsides to this solution are that (a) we will never be able to adequately describe all of the possible uses of a "comment" in one or two words and (b) a general name will remove all semantic meaning that comments have.
- remove the chat bubble icon that appears next to comments without renaming them. (To be honest, I'm not sure what meaning this visual aid is supposed to add to the source sheet. The only thing that I can think of is that it is meant to be a way to differentiate between "authoritative" sources and the author's personal opinions.) This would remove some of the visual awkwardness of using a comment as a section header, but does not address the semantic concerns. One potential upside to doing this is that it makes the presentation of the source sheet more consistent across the various ways of displaying it (in print, on Google Drive, etc.).
- create an entirely new type of source called a "Section Header" (or something of that nature). This new source type would behave nearly identically to a comment (i.e. it is not numbered or boxed) except that there would not be a chat bubble icon next to it. Perhaps it can also have its own default styling (e.g. centered and italicized, centered and underlined). Additionally, I believe that this approach closely relates to issue #116; Section Headers can serve as a signal for the numbering to restart.

What do all of you think? Is this a legitimate issue or am I dramatizing the confusion that is caused by using comments as titles? If you deem it to be an issue that needs to be addressed, what do you think is the most effective way to solve it? I would be more than happy to implement whichever approach we agree upon.

\- Palmer

**Comment by rneiss** [comment]
**A.** We already do have an optional title field on all sources.

You can access it thusly:
> 1. Click on an added source/text to make it active.
> 2. Click Format -> Add Source Title
> 3. Edit said title.
> 

**B.** We have this generic text option. We call it "Text" -- if you shift the view from bilingual to english, it basically functions just as desired.

**C.** re: chat bubble -- the comment feature primarily serves for those source sheets that are more collaborative in function. It's a very nice indicator in that particular use case, but yes, folks were using comments in this fashion previously.

**D.** this idea of an outline form (w/ section breaks) is intriguing, but I think it's functionally different than the issue specifically outlined here which I think is addressed in case A. 

Open to other opinions however...

**Comment by pzp1997** [comment]
**A.** Wow! I did not realize that this was possible. I'll have to show this to the person who requested the feature to see if this satisfies his request (sounds promising).
**B.** I suppose that "Text" is the generic text option. But there is a problem with using "Text" as a section header (and I'm sure I could think of other use cases where this would be a problem as well)-- it will be boxed and numbered as if it were another source.
**C.** That makes a lot of sense. I was not thinking of collaborative source sheets yesterday.
**D.** I agree that case A addresses this issue, so I'm going to close it for now. Do you think that despite being tangential to this issue, the option of being able to lay your sheet out in an outline form of some kind would be a useful feature? Should I open a new issue to discuss?
