### ISSUE TITLE
Commentary bar removes all commentaries but one when scrolling

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#264]
When a user clicks on a section, selects a commentary, clicks to go back to "Connections", and selects a second commentary, the bar at the top of the commentaries section lists the names of both commentaries, and the contents can be switched between clicking the names. However, when the user scrolls in the main content (not the commentaries themselves) to a different section, all but one of the commentary names disappear.

**Comment by blockspeiser** [comment]
Thanks for the report! This bug is now fixed.
