### ISSUE TITLE
Error at / python 2.7.5

### ISSUE THREAD

**Issue by salexfo** [Sefaria/Sefaria-Project#280]
Hi, after following installation instructions here is what I get:

Environment:

Request Method: GET
Request URL: http://sefaria.local:8000/

Django Version: 1.4.5
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'emailusernames',
 'reader',
 'sheets',
 'sefaria.gauth',
 'captcha',
 'django_mobile',
 'django.contrib.admin')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django_mobile.middleware.MobileDetectionMiddleware',
 'sefaria.system.middleware.ProfileMiddleware',
 'django_mobile.middleware.SetFlavourMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  101.                             request.path_info)
File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py" in resolve
  300.                     sub_match = pattern.resolve(new_path)
File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py" in resolve
  196.         match = self.regex.search(path)
File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py" in regex
  162.                 compiled_regex = re.compile(self._regex, re.UNICODE)
File "/usr/lib64/python2.7/re.py" in compile
  190.     return _compile(pattern, flags)
File "/usr/lib64/python2.7/re.py" in _compile
  242.         raise error, v # invalid expression

Exception Type: error at /
Exception Value: nothing to repeat

as per stackoverflow it seems that it might be a bug in python 2.7.5

Is it the case? Should I upgrade to python 2.7.6+?

**Comment by rneiss** [comment]
Can't hurt ;)

Yes please try. Let us know -- this is a new bug for us.

**Comment by blockspeiser** [comment]
@salexfo Did upgrading Python fix this issue for you?

**Comment by blockspeiser** [comment]
I'm closing this Issue since we haven't heard anything more about it and we're now on Python 3.
