### ISSUE TITLE
punctuation

### ISSUE THREAD

**Issue by rafi266** [Sefaria/Sefaria-Project#295]
Is there a possibility of getting the punctuations in the sefaria talmud- as seen in the Steinsaltz Koren hard copy?

**Comment by rneiss** [comment]
We're definitely hoping to add Nikud and punctuation in the future.

**Comment by rafi266** [comment]
thanks.. Also- I sent a few corrections to the corrections link- hope its
the right place to send to.



----------------------------------------------------
"Ma gavte la nata"
