### ISSUE TITLE
Version links aren't proper links

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#302]
In the "Versions" tab in each text's Table of Contents, the links to each version are bare spans with javascript handlers. Because they aren't `<a>` elements using href=..., user's can't open the links in new tabs/windows, or copy the URL, or even access it at all when using only a keyboard.  (That last issue could theoretically be solved with tabindex attributes.)

**Comment by YairRand** [comment]
This also applies to the links in the "Parasha" tab, for the relevant works.

**Comment by rneiss** [comment]
These issues are fixed in the `accessibility` branch which will be merged into master and onto production shortly. The specific commit I believe is this one: https://github.com/Sefaria/Sefaria-Project/commit/30d6ad168d62f85d78b3cd8882c7abc95c1446e5
