### ISSUE TITLE
Viewing a source sheet then logging in redirects to a bad URL

### ISSUE THREAD

**Issue by mfessler** [Sefaria/Sefaria-Project#305]
I was just logged out, viewing a source sheet, and tried to log in - after doing so, I was redirected to a URL "http://varnish/sheets/48133". (Obviously I was able to go back to the original sheet, but the redirect should be fixed)

**Comment by EliezerIsrael** [comment]
Thanks for the report.  

There were a few hours yesterday where we saw this behavior as we were upgrading out https security.

It should be fixed now.
