### ISSUE TITLE
Sefaria Source Sheet Not Loading

### ISSUE THREAD

**Issue by goingpostel** [Sefaria/Sefaria-Project#330]
I made a private source sheet, but non of the texts are showing up on the sheet. Additionally, I can't edit any previous sheets I've made or export them to google drive. It seems like the sheets are totally unresponsive.

**Comment by blockspeiser** [comment]
Thanks. We just noticed a bug with the most recent release that would cause certain browsers to error out like this.

We've just patched that bug -- could you try again now and let us know if you're still having errors? If you do still have errors would you mind sending the URL of the sheet you're having trouble with to hello@sefaria.org and we'll take a deeper look.
