### ISSUE TITLE
question about sugyot structure

### ISSUE THREAD

**Issue by Mslaster** [Sefaria/Sefaria-Project#338]
@EliezerIsrael: I was wondering what criteria you used to break a Gemara's text into units of sugyot? (https://github.com/Sefaria/Sefaria-Project/tree/master/data/sugyot)

**Comment by EliezerIsrael** [comment]
All of our division data comes in one way or another from the Steinsaltz / Koren versions.

Originally, we broke up our segments in Talmud by the punctuation of the Steinsaltz, making for very small segments.  You can still see this in the mesechtot that do not have the full English translation - currently the end of Nezikin onward.

With the import of the English, we converted our segmentation to match the printed segmentation - these are roughly sentence/short paragraph level divisions.  You'll see this on everything from Berakhot to Sanhedrin, currently.

Additionally, we have data for the sugya divisions, as they are broken up in the Koren version.  It is not reflected on our website anywhere, but it's available in the codebase, here: https://github.com/Sefaria/Sefaria-Project/tree/master/data/sugyot
This data currently exists for 18 mesechtot; as we continue to import that Koren English and Hebrew, that data should expand to cover all of the Bavli.
