### ISSUE TITLE
"Modern Works" is confusingly ordered

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#339]
The section "Modern Works" is confusingly ordered. For example, it lists volumes IV-VI of "Contemporary Halakhic Problems", followed by three parts of "Redeeming Relevance" (one of which is incidentally missing a subtitle), followed by volumes I-III of Contemporary Halakhic Problems.

**Comment by blockspeiser** [comment]
Modern Works is no more, and everything is generally less confusingly ordered now :)
