### ISSUE TITLE
Top of the scrollbar is hidden when reading

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#340]
The .readerControls element hides the top of the main vertical scrollbar, including the scroll-up arrow that exists in some OSs. This makes navigation more difficult for some users, and the layout makes the PageUp/PageDown keys scroll by more than one (visible) page's worth, causing the reader to miss some content.

**Comment by blockspeiser** [comment]
Fixed recently. We should longer have any headers that float on top of a scrollable area.
