### ISSUE TITLE
Dictionary lookup is called on English words

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#346]
Double-clicking on a word in an English work or an English translation of a Hebrew work results in a dictionary lookup appearing, with no results (as the dictionary doesn't go in that direction).

**Comment by alis0nc** [comment]
I'm taking a look at this. Wondering if we can disable calling the lexicon on highlight if we highlight the english.
I also found the related issue that if you double click on a lexicon entry in things that are not the Tanakh, it says "no definitions found". 
![screenshot from 2017-08-30 11-51-01](https://user-images.githubusercontent.com/4296609/29882087-072b46fa-8d7a-11e7-810a-40eff7ff6c4c.png)
![screenshot from 2017-08-30 11-54-28](https://user-images.githubusercontent.com/4296609/29882091-09eed910-8d7a-11e7-9fd9-c963e652ea4c.png)

**Comment by blockspeiser** [comment]
This is fixed.
