### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by yitzchoklowy** [Sefaria/Sefaria-Project#349]
will the project work with python 3?

**Comment by EliezerIsrael** [comment]
It's currently a Python 2.7 project.  We haven't given it a swing with Python 3 in a while; I imagine that it would take some work to make it Python 3 ready.

**Comment by yehosef** [comment]
I think this should be reopened considering python 2.7 is EOL on January 1st, 2020.

**Comment by EliezerIsrael** [comment]
Quite so!  
The `p3` branch is up-to-date, and working with Python 3. 
We plan to promote it to master once we're satisfied with the devops and testing sides of things.
