### ISSUE TITLE
Focused block moves depending on top-borders

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#350]
When a user has clicked on a block of text (making the text background grey), and then scrolls, the focused block changes to the next block if the top of the screen is lower than the top of the block of text. (Or, in practice, within ~100px of the top.) This means that the focus will often move forward long before the next block of text is even at all visible. See for example, [here](https://www.sefaria.org/Mishneh_Torah,_Repentance.1) (with both languages shown), where the text block can span the whole screen and then several hundred pixels past both the top and bottom, with the focus being moved to a text block nowhere near in view.

A related issue exists with chapter marker at the top, which changes before the new chapter is even visible. This can cause substantial confusion about what chapter one is viewing.

**Comment by blockspeiser** [comment]
I made some changes on the last deploy that I hope fix this. 

We're now checking the top edge of a segment of text AND the bottom edge. The highlight lands on the first segment whose top edge if bellow a threshold OR whose bottom edge is bellow the middle of the screen. This prevents a segment from lossing highlight unless the top of the following segment is above the middle of the screen.
