### ISSUE TITLE
"Version Settings" and "File Format" aren't translated

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#351]
In a work's Table of Contents, at the bottom of the "Versions" ( / "גרסאות" ) section, the texts "[Version Settings](https://github.com/Sefaria/Sefaria-Project/blob/585935056248a536cccc019d96361f201c906c84/static/js/ReaderTextTableOfContents.jsx#L199)" and "File Format" don't get translated to Hebrew when the user's site language is set to Hebrew.

Related issue: The hovertext for the search box is also always in English.

**Comment by jaykaron** [comment]
Also, it seems "Version Settings" and "File Format" have already been translated.
