### ISSUE TITLE
Can't click on anything

### ISSUE THREAD

**Issue by opengemara** [Sefaria/Sefaria-Project#360]
I've tried this on Chrome, Chromium and Firefox (both 56 and 57):

Go to (say) https://www.sefaria.org/Berakhot.5a . Click on text - normally a sidebar would pop up with Maarei Mekomos. Now it doesn't. Neither does the Aא work in the top corner.

**Comment by edamboritz** [comment]
Hi, there might have been some connection issues. 
I saw the problem briefly and then it corrected itself. 
Could you please try again? 
If that doesn't work, id recommend clearing your browser's cache/cookies and performing a hard reload of the page.
