### ISSUE TITLE
Search box is cleared upon loading

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#365]
Frequently, the first thing a user looks for when going to Sefaria is the search box in the top-left corner. The user clicks on it, and starts to type the name of the desired text.

When the page finishes loading, the text box is emptied, and the box unfocused, so the user must start again. This can happen as much as a full second after the search box becomes visible, in my experience.

**Comment by elico** [comment]
@YairRand is this issue still open?
The search-box becomes empty when you "open" a new page.
If I will try to enter the page: `יבמות קכא ב`
So when I will choose the page the url will change into: `http://sefaria/Yevamot.121b?lang=he`
Maybe the solution would be to add another query argument that will have the search-box value?
I am not sure what was the issue and probably what the right solution.

**Comment by YairRand** [comment]
This issue appears to be fixed now. The search box is no longer cleared in the middle of loading.
