### ISSUE TITLE
"Epistle of Rav Sherira Gaon" returns Internal Server Error

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#371]
The page for the [Epistle of Rav Sherira Gaon](https://www.sefaria.org/Epistle_of_Rav_Sherira_Gaon) shows "Internal Server Error". The content is inaccessible.

(Sorry if this is a redundant report. The error message says that an email was automatically sent to the developers, but the error has been occurring for a while so I thought that it might be helpful to start a ticket just in case the automatic report got overlooked or didn't go through somehow...)

**Comment by JonMosenkis** [comment]
Thanks, for pointing this out. Should be fine now.
