### ISSUE TITLE
Version links are broken links

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#382]
In the Table of Contents for a work, the links under the "Versions" heading have hrefs that lead to 404s. Normally, resolving of these links is taken over by JS, which seems to ignore the actual href of the link, but if a user wants to open it in a new tab or window, the destination URL is the title of the version, eg https://www.sefaria.org/Jewish%20English%20Torah , which shows "Page Not Found".

**Comment by nsantacruz** [comment]
Thanks for the report. We've filed the bug.

**Comment by nsantacruz** [comment]
Fixed in our `test` branch. Should be on production soon.
