### ISSUE TITLE
How to set default site interface to Hebrew?

### ISSUE THREAD

**Issue by elico** [Sefaria/Sefaria-Project#383]
I have written the next Sefaria installation script:
http://gogs.ngtech.co.il/elicro/sefaria-ubuntu-installation/src/master/install.sh

And it works great.
I was trying to search and understand the right way to statically set the default site interface language to hebrew but didn't managed yet to do so.
I can set it per user but I want it to be global for the whole site by default and if a user want to change it he will be able to.
How do I set the default interface to hebrew?

**Comment by blockspeiser** [comment]
You can set the global default with the DOMAIN_LANGUAGES variable in `local_settings.py`.

It's a little confusing, but there is an example in `local_settings_example.py`. https://github.com/Sefaria/Sefaria-Project/blob/master/sefaria/local_settings_example.py#L129

For local development I usually do something like:

DOMAIN_LANGUAGES = {
    "http://localhost:8000": "english",
    "http://0.0.0.0:8000": "hebrew",
}

**Comment by elico** [comment]
@blockspeiser I tried what you suggested before I began to ask...
I tried to analyze what is causing it and I found out that the browsers sends "Accept-Languages: en-US,en..." and this is causing the interface to be sent in English due to a "strict" request of the client.

What I did eventually is added something to my nginx reverse proxy:
```
        location / {
                if ($http_cookie !~ 'interfaceLang') {
                        add_header Set-Cookie "interfaceLang=hebrew";
                        rewrite ^(.*)$ $1 permanent;
                }
                proxy_pass http://sefaria.local;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;

        }
```
And it might not be the most ideal solution but it works for me so.
If you can take my script:
http://gogs.ngtech.co.il/elicro/sefaria-ubuntu-installation/src/master/install.sh
and apply anything to it that will make the default language hebrew it would help me to understand what I did wrong.
I have tested this on a Windows: Firefox, Chrome, Edge, Internet Explorer.
And also on my mobile with Firefox and Chrome.

**Comment by blockspeiser** [comment]
Off the bat, we've never really run Sefaria served directly by ngnix. We use the Django test server locally and Apache on production (although nginx does also play a role in our prod stack also). 

Let me say more after I get a chance to look at your script.

thanks

**Comment by elico** [comment]
@blockspeiser The service is not running under nginx but as reverse proxy to sefaria running purly django on port 80.
You will probably understand how it all works since it's really a simple installation.
My setup has one frontend nginx server with a local public IP and the backend is another local internal IP address and it's like a varnish in-front of the django but only with nginx running without caching at all.
I was looking for instructions on how to setup Sefaria with varnish but didn't had enough time yet to look how to put it all together.

**Comment by blockspeiser** [comment]
Hmm, not sure I fully understand the your setup. We use a lot these services in someway in our production stack, but sounds like not quite the same way. 

We've generally only every supported people in the Dev server, and them left them to themselves to figure out alternate stacks. We haven't documented our prod stack publicly as a security precaution. 

We're working on Dockerizing out whole stack. Once that's done I think a lot of these question should be solved.

**Comment by elico** [comment]
I am wondering if the docker compose can work locally for an AI agent to be able to access it via LAN instead of over the WAN connections?
