### ISSUE TITLE
Upload a pdf to sourcesheets

### ISSUE THREAD

**Issue by DanFM** [Sefaria/Sefaria-Project#385]
Is it possible to introduce a feature where I could upload a pdf to my sourcesheet and avoid error-prone cutting and pasting?

I often need to bring in external text from a pdf and I find it very difficult to accomplish.

Thank you so much.
Daniel

**Comment by rneiss** [comment]
Unfortunately due to the proprietary nature of pdf files and the difficulty in extracting text from them in general, we haven't created a tool to support this sort of functionality.

**Comment by DanFM** [comment]
Thank you for this reply.

I also tried to convert to jpg, but was not successful adding it to the
source-sheet.

**Comment by rneiss** [comment]
Adding an image via the media button seems to be working fine. 

Let us know if you're having any trouble.
![screen shot 2018-02-21 at 3 18 53 pm](https://user-images.githubusercontent.com/1596539/36505909-a5a7f8ee-171a-11e8-9994-736b008d25bd.png)

**Comment by DanFM** [comment]
Can you upload from your computer or does it have to be from a public site?

**Comment by rneiss** [comment]
If you click on "Upload an image" like in the screen shot above, you can upload directly from your computer.

**Comment by DanFM** [comment]
Thank you.
When I try again I will get back to you.

**Comment by DanFM** [comment]
Thank you for helping with this.
I tried uploading a PNG file, but received an error.

https://github.com/Sefaria/Sefaria-Project/wiki/Source-Sheets-FAQ   has the
following line
 Currently, images are only support in Source Sheets by embedding images
that already have a public link on the web.

**Comment by rneiss** [comment]
The wiki is wrong. I'll update that now.

Can you share the error you received?

**Comment by rneiss** [comment]
Updated Sheet directions are available here: 

https://github.com/Sefaria/Sefaria-Project/wiki/Database-and-Source-Sheet-Tutorials#creating-and-building-a-source-sheet

**Comment by DanFM** [comment]
Thank again for  this help.  I don't know where to find the error number.
I'm pasting a screenshot of the error message below.

[image: Inline images 1]

**Comment by DanFM** [comment]
Thank you for your help on this.
I'm not sure if you can see the pasted screenshot so I am writing it out
below.
I don't see the error number to send you.

"Unfortunately an error has occured. If
You've recently edited text on this page you
may want to copy your recent work out of
this page and click reload to ensure your
work is properly saved."
