### ISSUE TITLE
Feature request: Subheaders

### ISSUE THREAD

**Issue by chaimkut** [Sefaria/Sefaria-Project#391]
Aside from the title of the Source Sheet, I would also like the ability to insert sub-headers to further divide sections of the source sheet.

**Comment by rneiss** [comment]
This functionality exists.

![mar-19-2018 00-37-14](https://user-images.githubusercontent.com/1596539/37579698-bf3c828c-2b0d-11e8-91f2-504fcdd7fa86.gif)

Click on the source you wish to add the custom title to, click on **format** on the menu bar, then **add source title**, and go to town. 

To remove it, just delete all the text in the custom title.

**Comment by chaimkut** [comment]
Hi,
The intent of the feature request is not to customize a source's title text.
The intent of the feature request is to divide the source sheet into subsections. For instance:

# Source sheet title: Holidays in the Jewish Calendar

## Subsection: Biblical
### Pesach sources
.....
### Shavuot sources
....

## Subsection: Rabbinic
### Purim sources
....
### Chanukah sources
....
## Subsection: Local
### Seharane sources
....
### Feast of Yitro sources
....

**Comment by chaimkut** [comment]
I see now that the feature exists. Looks great, I'll be sure to use it.
