### ISSUE TITLE
UI for Comparing Text Versions

### ISSUE THREAD

**Issue by blockspeiser** [Sefaria/Sefaria-Project#40]
From the about menu of any text with multiple versions, add a "Compare to" menu which allows the user to select another version.

Show both versions side by side similar to the bilingual view.

Should change top left buttons into a compare mode (lang controls don't make sense in this context, but layout might) which an option to exit compare mode or choose another version.

**Comment by yishairasowsky** [comment]
@nqeron how did this go? i would be excited to hear any progress.

**Comment by EliezerIsrael** [comment]
We did develop a tool like this in house, behind the curtains.  We use it to compare two text versions and see what the differences are. 

As for now, it's not anything that we are looking for on the frontend.  I'm going to close.

**Comment by blockspeiser** [comment]
We've also developed a way for users to be able to compare text versions -- in the sidebar you can click Versions to open different versions. You either open in a segment view where the text of the version follows along as you scroll, or you can open another version in outs own complete side by side panel (although they doesn't do automatic scroll syncing).
