### ISSUE TITLE
Feature request: Commentator genealogy

### ISSUE THREAD

**Issue by chaimkut** [Sefaria/Sefaria-Project#419]
A fun feature would be the creation of a commentator genealogy similar to the [Mathematics Genealogy Project](https://www.genealogy.math.ndsu.nodak.edu/) which visually displays the student-teacher relationships between commentators. A simple database exists in Wikipedia -- example 
https://he.wikipedia.org/wiki/%D7%A8%D7%9E%D7%91%22%D7%9F
which includes a list of students, teachers of a particular commentary (Ramban). It looks like this would have to been manually scraped. Perhaps other databases of this information exist.

Something possibly easier would be a graph similar to the Tanach-Talmud interactive feature. For instance, searching over the entire set of writings of the Ritva, seeing that he has many quotes from the Ramban, less from Rashba, etc. one could understand who were his primary influences. This would be done over the set of commentators to understand the flow of Torah knowledge through history. This of course all depends on how well tagged the texts are...

**Comment by EliezerIsrael** [comment]
It's a good idea.
We have some of the basis of it collected already.  See for example https://www.sefaria.org/person/Ramban

Rendering an influence tree automatically is harder than it first appears.  True trees, where each node has exactly one parent (teacher, in this case), have a number of ways to visualize cleanly and beautifully.  Once nodes can have more than one parent, the data structure is no longer a tree but rather a directed acyclic graph, which is *much* harder to render graphically in any dependably beautiful way.  Small families - of a few generations - are more likely to render cleanly.  

You can see an example of our ongoing experiments here - a graph of the main Tanaim and Amoraim: https://www.sefaria.org/visualize/talmudic-relationships
