### ISSUE TITLE
Local copy of Sefaria hangs on a simple page with commentaries.

### ISSUE THREAD

**Issue by elico** [Sefaria/Sefaria-Project#426]
I have built a VM for local usage with the next repo:
> http://gogs.ngtech.co.il/elicro/sefaria-ubuntu-installation

the installation script is for Ubuntu 16.04 and run's smoothly from start till the end.
After I am accessing the VM from any web-browser with the next url:
- <https://sefaria.org.il/Judges.5.18?lang=he&with=Commentary&lang2=he>

But locally:
- <http://sefaria/Judges.5.18?lang=he&with=Commentary&lang2=he>

The browser just get stuck for couple minutes and stays this way.
I have seen a note about a bug that might be related but I wanted t make sure that it should or shouldn't happen.

**Comment by elico** [comment]
I have upgraded my local sefaria vm and will test this issue again.

**Comment by EliezerIsrael** [comment]
Ok.  Let us know.

**Comment by elico** [comment]
@EliezerIsrael Works great!
