### ISSUE TITLE
calander api

### ISSUE THREAD

**Issue by yitzchoklowy** [Sefaria/Sefaria-Project#428]
is there a way to get the calendar class as an api? it would be very helpful to be able to get the weekly parsha, daf hayomi, etc.

**Comment by yitzchoklowy** [comment]
Thanks so much. I was looking in the wiki so I didn't see it. Will check it out.

**Comment by yitzchoklowy** [comment]
ok, so my question is when does the calander change to the next day? I was expecting it to change at midnight but apparently this is not the case. checking the api now (aug 2 12:20 am) it gives me daf hayomi of zevachim 110, while aug 2 should be zevachim 111. same for 929 it shows genesis 14 while it should already be 15.

**Comment by edamboritz** [comment]
Hi, the calendar is currently adjusted toward our server's time. So it behaves as if everyone is in US Pacific time. 
We are working on adjusting it so it gives a more accurate time for each user!

**Comment by yitzchoklowy** [comment]
Thanks.

I would suggest returning the date along with the calander so we can check from the api result what date it is for and implement logic to make sure we are getting the correct date.

**Comment by edamboritz** [comment]
Thanks for the suggestion! We'll add that in a future release.
