### ISSUE TITLE
Source Sheet: Filter out Conservative/Reform papers

### ISSUE THREAD

**Issue by benadavid** [Sefaria/Sefaria-Project#436]
As a user, I would like to be able to look at source sheets without having to guess whether it is written in a conservative or reform ideology. Therefore, when creating a source sheet, a user should be able to specify whether his source sheet is orthodox, conservative, reform, or other, in order to then implement a filter for readers.

**Comment by emilyaviva** [comment]
I'd like to be able to filter out sources without having to guess whether the author views me as a human being or not.

**Comment by benadavid** [comment]
Being an orthodox Torah follower does not mean I'm anti-human. Your movement is less than a century old.

**Comment by benadavid** [comment]
> I'd like to be able to filter out sources without having to guess whether the author views me as a human being or not.

Being an orthodox Torah follower does not mean I'm anti-human. Your movement is less than a century old.

**Comment by emilyaviva** [comment]
I strongly oppose adding such a filter as this. Many (all?) sources cannot be categorized as "orthodox" or "reform" or whatever. I'm not even sure what that /means/. Is the Shulchan Aruch an "orthodox" source? Meaningless. A source is a source. If it's not sufficiently kosher for you, you should be able to judge that for yourself.

**Comment by EliezerIsrael** [comment]
Sefaria is an open platform, and will be for the foreseeable future.  Authors can pro-actively tag their sheets with whatever they want, in order to make them more findable.  Users are encouraged to find the texts that most resonate with them, and do their best to be tolerant of others.
