### ISSUE TITLE
Metatagging Sefaria - Stemming and Lemmatization

### ISSUE THREAD

**Issue by rosenjcb** [Sefaria/Sefaria-Project#446]
I've been a fan of Sefaria so far and I've recently had the chance to talk to a peer about it. We both agreed that we really wish to enrich the project with greater metadata and increase its capabilities by implementing including features like stemming and lemmatization. I know my way around a daf but I'm not exactly fluent in Babylonian Aramaic. Would anyone with great Hebrew/Aramaic fluency be willing to cooperate with me on such an endeavor? I think this would benefit greatly for anyone wanting to engage in Torah study.

**Comment by EliezerIsrael** [comment]
I'm sorry that this question didn't get traction. There are individuals and groups that are working on these issues.  Most notable in my mind is https://dicta.org.il/, and the researchers there.
