### ISSUE TITLE
Which is the endpoint for targum of a given parasha ?

### ISSUE THREAD

**Issue by benjaminb10** [Sefaria/Sefaria-Project#456]
Hi,
How can I get the Targum Onqelos for a given parasha.
Example with this endpoint: https://www.sefaria.org/api/texts/Exodus.6.2-9.35
I see English and Hebrew texts.
Do you plan to add Targum here?

**Comment by nsantacruz** [comment]
You only requested Exodus. You can request text for any book in our library.
For example https://www.sefaria.org/api/texts/Onkelos_Exodus.6.2-9.35

**Comment by benjaminb10** [comment]
Great, thanks!
