### ISSUE TITLE
Search box can be confusing

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#467]
Sefaria does not exactly have a prominent search box. There is no search box in the body of the front page or table of contents, and the search box in the corner has no border or separate styling indicating that it is a box that text can be typed into, or that the word "Search" is associated with a distinct box at all. If a user tries to first click on the associated icon, nothing happens.

I would recommend changing the styling of the search box to be a distinct container. The undistinguished search box is very unusual; I can't think of any other site that doesn't distinguish the search box with a border, a shadow, and/or distinct coloring.

I think it might also help to change the behaviour of the search button so that when clicked when the search box is empty, the search box is focused, perhaps with an extra visual indicator (eg a flash of a colored border and a styling change, like Instagram does). Alternatively, the user could be brought to a dedicated search page (like for example Wikipedia does).

**Comment by nsantacruz** [comment]
These are totally reasonable suggestions. I'll add this to our list of
feature requests and bring it up with our UX designer.

**Comment by EliezerIsrael** [comment]
I believe that recent work addresses most of these issues.
