### ISSUE TITLE
The ubuntu standalone instance installtion was updated.

### ISSUE THREAD

**Issue by elico** [Sefaria/Sefaria-Project#468]
I have verified that the standalone Ubuntu based instance installation works with the current project:
http://gogs.ngtech.co.il/elicro/sefaria-ubuntu-installation

To install just clone the git into an Ubuntu 16.04 or 18.04 VM or Machine and run the install.sh executable while there is network and you should have a local working sefaria instance.
Just make sure you change the wget command for the dump from my server to google which is much faster for most of the users.

**Comment by edamboritz** [comment]
Thanks!
