### ISSUE TITLE
Adding Talmud [or any text] to source sheet via highlighting

### ISSUE THREAD

**Issue by herlands** [Sefaria/Sefaria-Project#47]
(Note: Perhaps this would be better for a google groups discussion - not sure)

While I appreciate the semantic and sectional divisions provided by sefaria, many times I only want to use a section of a source, a fragment of a gemara, or 2.3 mishnaiot. This is especially true for gemara sources where my sources rarely fit into a predefined semantic block. To that end it would be great if I could add to a source sheet by simply highlighting the fragment I am interested in and clicking (right clicking?) to add to a source sheet.

One issue related to this is how to copy over the corresponding translation. I suggest a greedy method of copying over translation to ensure that the fragment is covered. For example, if I take a fragment from the end of verse 1 through the first half of verse 2, the translation for the entirety of verses 1+2 should be copied over to my source sheet.

**Comment by rneiss** [comment]
This feature now exists.
