### ISSUE TITLE
Typo in va-Yakhel Ex 35:7 שִׂטִּֽים

### ISSUE THREAD

**Issue by NevilleStern** [Sefaria/Sefaria-Project#471]
וְעֹרֹ֨ת אֵילִ֧ם מְאָדָּמִ֛ים וְעֹרֹ֥ת תְּחָשִׁ֖ים וַעֲצֵ֥י שִׂטִּֽים׃

**Comment by ShmuelW** [comment]
Hi Neville,

The Hebrew Tanakh on Sefaria is based on the Leningrad Codex - via https://www.tanach.us/Tanach.xml.

As a matter of policy, Sefaria will not alter the Leningrad version to match other variants. 

Sincerely,

Shmuel Weissman
MANAGER of TEXT ACQUISITION & TEXT QUALITY
shmuel@sefaria.org | sefaria.org
