### ISSUE TITLE
Link Explorer graphic doesn't appear for most connection types

### ISSUE THREAD

**Issue by donielf** [Sefaria/Sefaria-Project#472]
<img width="1263" alt="screen shot 2019-02-25 at 11 56 33 am" src="https://user-images.githubusercontent.com/47986164/53354290-781f3e80-38f4-11e9-9b47-78c68b7c2cec.png">

The above pictures shows that the graphic doesn't appear on the Talmud & Tanach page. This occurs on Talmud & Mishneh Torah and Talmud & Shulchan Aruch as well, but not the other four tabs. Perhaps it's an issue with Talmud connections?

I've tested this on Firefox and Safari with identical results. I'm working off of a Mac, latest OS.

**Comment by EliezerIsrael** [comment]
Thanks for pointing this out. 
It was a data error in a new Talmud guide that we uploaded.
Should be corrected now.

**Comment by donielf** [comment]
Can confirm that it works properly. Thank you!
