### ISSUE TITLE
Source Sheet: doesn't display highlights

### ISSUE THREAD

**Issue by StephenBerer** [Sefaria/Sefaria-Project#474]
Hi. I created a source sheet a few months ago: "a structural analysis of Beraysheet" that used highlighting to note the different types of knowledge being conveyed in the Torah text. Here's the link:
https://www.sefaria.org/sheets/134719?lang=bi
I just discovered it has 2 problems:
1. The highlights are only visible in edit mode. Viewers can't see the highlighted text!! All they see is the Torah text as it displays from a standard Tanakh page. Thus, it looks like I started to create a sheet, but never did any of the work!
2. The highlight codes are lost. There once was a  little table/graphic explaining what each color represented, so the viewer could understand the different types of knowledge being conveyed in the text.
So... What to do?
Thanks for your help.
Steve Berer

**Comment by EliezerIsrael** [comment]
I'm sorry to say that this is an experiment that didn't get a lot of traction.  We're removing the feature from future development.
