### ISSUE TITLE
Provide keyboard shortcuts for toggling language, vocalization

### ISSUE THREAD

**Issue by jbizzle** [Sefaria/Sefaria-Project#479]
For the desktop site at least, I'd find it helpful if there were a set of keyboard shortcuts to accomplish the same toggling available from the language selection dropdown. In particular, it'd be nice to toggle bilingual on/off, as well as to enable/disable vocalizations in the hebrew via a keystroke.

My personal motivation, if helpful, is to help me in preparing leyning, since I can quickly switch teamim and nikud on/off as I prepare the reading, without moving the page visibly or having to use the mouse.

Apologies too if this is in place already. I couldn't find the feature or discussion of it yet.

**Comment by EliezerIsrael** [comment]
Thanks for the idea.  We've noted it, and we're tracking it.   I don't think we've heard the request before, though.  I'm curious how widely appreciated this would be.

**Comment by baobabprince** [comment]
I think this may be useful feature.
If I want to use the site as Tikun Korim I want to show/hide the te'amim and nikud often. Keyboard shortcuts can make it easier.
