### ISSUE TITLE
About https://www.sefaria.org/api/calendars

### ISSUE THREAD

**Issue by loozyoni** [Sefaria/Sefaria-Project#480]
Hi,
Today parashat hashavua is Behukotay but when I send request from https://www.sefaria.org/api/calendars it returns Behar

**Comment by edamboritz** [comment]
Hi, the default behavior of the calendar API is to display disapora items. 
You can get the Israeli parasha by specifying: https://www.sefaria.org/api/calendars?diaspora=0
