### ISSUE TITLE
Production built on sefaria

### ISSUE THREAD

**Issue by eran-pinhas** [Sefaria/Sefaria-Project#492]
Hey guys :)

![image](https://user-images.githubusercontent.com/11258180/62319728-50d22c00-b4a7-11e9-84c7-fad19428fc7e.png)

Using production build should perform better.

from React's website:

> By default, React includes many helpful warnings. These warnings are very useful in development. However, they make React larger and slower so you should make sure to use the production version when you deploy the app.

**Comment by blockspeiser** [comment]
Thanks! This crept in recently all due to a single "r" that should have been an "R". It will be fixed on the next deploy.
