### ISSUE TITLE
Get the Gmarah portion of a Bavli segment

### ISSUE THREAD

**Issue by dimidd** [Sefaria/Sefaria-Project#498]
Shalom,

Is there an api method to get just the Gmarah portion instead of splitting manually? I.e
```
ind = sefaria.model.library.get_index("Berakhot")
seg = ind.all_section_refs()[0]
txt = seg.text('he')
st = txt.as_string()
txt.remove_html(st).split(u'גמ׳')[1]
```

**Comment by edamboritz** [comment]
Hi, 
From an API perspective, that way you are doing it is probably the best way. We don't actually distinguish programmatically between the Mishnah and Gemarra portions of the text. 

However, we do have a fodler of csv's that tell you what each ref is -
https://github.com/Sefaria/Sefaria-Project/tree/master/data/sugyot
This will basically tell you where each gemara and mishna in a Talmud tractate start and end. 

Hope this helps!

**Comment by EliezerIsrael** [comment]
(Hi @dimidd !  Nice to see your name pop up.  Curious what you're working on...)

**Comment by dimidd** [comment]
Hey Lev! How have you been? I'm dabbling in Aramic NLP, building on @nsantacruz 's  seminal work. Ping me if you're visiting JLM :)

**Comment by dimidd** [comment]
Hi again,

I'm a bit confused about the sugyot. E.g. what does the range 1-5 mean in Berakhot 2a:1-5?
Also, in the webpage each section is highlighted separately, how does it work on the server-side? Is it possible to query mongo for these partitions?

**Comment by nsantacruz** [comment]
We break up a Talmud Amud into paragraphs. The paragraphs are denoted by the 1-5. So Berakhot 2a:1-5 means the first 5 paragraphs on Berakhot 2a.

This is reflected in our Mongo database. You can make an API call for https://www.sefaria.org/api/texts/Berakhot.2a.1-5?context=0 which will return an array of length 5 for the `text` and `he` fields.

In our Python code, you can write `r = Ref("Berakhot 2a:1-5")` and you'll get a ref for this exact range. 

Is that what you were asking or do you actually want to query the Mongo database directly?

**Comment by dimidd** [comment]
Thanks! That's exactly what I need, but could you provide some minimal context of how to get `r = Ref("Berakhot 2a:1-5")`?

**Comment by nsantacruz** [comment]
I'm not sure what you mean. In order to import the basic Sefaria model, you can do `from sefaria.model import *`. That will import `Ref` as well as many other classes that are part of our model.

**Comment by BoazDavid23** [comment]
Composed in Talmudic Babylon (c.450 - c.550 CE). Temurah (Substitution) belongs to the fifth order, Nezikin (The Order of Damages) and discusses the laws of what happens if an animal is substituted for an animal dedicated for a sacrifice. It has seven chapters says this for Temurah

    On Monday, 2 December 2019, 08:18:17 GMT-7, Noah Santacruz <notifications@github.com> wrote:  
 
 
I'm not sure what you mean. In order to import the basic Sefaria model, you can do from sefaria.model import *. That will import Ref as well as many other classes that are part of our model.
