### ISSUE TITLE
Temurah in both the talmud and mishnah

### ISSUE THREAD

**Issue by BoazDavid23** [Sefaria/Sefaria-Project#501]
Says it the fifth order of nezikin but it should says Kodashim instead

**Comment by BoazDavid23** [comment]
Sorry if i confuse anyone here what it say for temurah: Composed in Talmudic Babylon (c.450 - c.550 CE). Temurah (Substitution) belongs to the fifth order, Nezikin (The Order of Damages) and discusses the laws of what happens if an animal is substituted for an animal dedicated for a sacrifice. It has seven chapters

**Comment by EliezerIsrael** [comment]
Thanks for this!  I'm putting the changes through now.
