### ISSUE TITLE
Option to open "Read More" button on Pop-Up on a new tab

### ISSUE THREAD

**Issue by jlazoff** [Sefaria/Sefaria-Project#503]
Hi Sefaria Team,
Big fan of your work, and would love a code review and merge. I was not able to publish my branch to your repo if you allow new members, happy to join. 

The read more button on your pop up is taking users away from the site, so the option would be nice to send users to a new tab instead.

Great work!

**Comment by EliezerIsrael** [comment]
Hi!

You should be able to submit a pull request from a fork.  That's that best way to contribute code. 
I'm trying to understand your issue, though.  In what context is the pop-up?  I imagine that the code will make it all clear...

**Comment by jlazoff** [comment]
<img width="1073" alt="Screen Shot 2019-12-04 at 4 14 24 PM" src="https://user-images.githubusercontent.com/13966291/70186051-0c56d700-16b9-11ea-82ca-9773e253dc68.png">

Forgot to replace one of the variable names in the screenshot... 

Not sure why I can't check my branch in, but it's ok - this is a small one.

I would love to collaborate with you and expand this plugin. I was thinking we could expand the rabbis' section and include it with this script. Would you be interested in working on a project like that together?

**Comment by blockspeiser** [comment]
Hi @jlazoff -- this is a good change, I agree we should be opening links in a new tab. Would you like to submit this change as a pull request so you can be listed as a contributor? Thanks.

**Comment by jlazoff** [comment]
Hi @blockspeiser , you can go ahead and push it 👍
