### ISSUE TITLE
Translation is off on Shulchan Arukh, Orach Chayim 629

### ISSUE THREAD

**Issue by bentzis** [Sefaria/Sefaria-Project#505]
There is a mismatch on the translation. It doesn't match up in some cases, some parts have the wrong translation and there's some translated text that isn't in the original Hebrew version.

**Comment by JonMosenkis** [comment]
Please see our FAQ regarding issues with translations.
https://github.com/Sefaria/Sefaria-Project/wiki/General-FAQ#what-do-i-do-if-i-spot-a-mistranslation-or-a-discrepancy-in-a-translation
