### ISSUE TITLE
Is it possible to persist a certain configuration of commentaries?

### ISSUE THREAD

**Issue by YisraelV** [Sefaria/Sefaria-Project#514]
Hi. Thanks for a great app.

I'm using the IOS app. I often open Tanach, then Rashi, then Ramban then Iben Ezra. Or I open Talmud, then Rashi then Tosfot. Is it possible to persist my session so next time I use the app all these commentaries will be open already?

**Comment by blockspeiser** [comment]
We don't currently have a way to do this. It's a good suggestion, but would require some thinking about how to implement the UI around when and how open commentaries get cleared so they don't just build up forever. Thanks.
