### ISSUE TITLE
Italian translation listed as English

### ISSUE THREAD

**Issue by MattiaHalevi** [Sefaria/Sefaria-Project#518]
Hi,

I have started to translate Genesis into Italian (as here: https://github.com/Sefaria/Sefaria-Project/wiki/Adding-Non-English-Translations), but unlike other foreign languages versions listed (French, Hebrew, German, Russian), mine result listed as English translations. 

Why is it so?

**Comment by MattiaHalevi** [comment]
EDIT: I understood that the two character language code in brackets had not to be written in caps lock. Now here is the issue; as I update that, the old versions with the caps letters are still listed as English versions. How can I delete these?

**Comment by ShmuelW** [comment]
Hi Mattia,

The superfluous versions have been deleted. In addition, I've combined all individual chapters (eleven of them) into a single version, which I'll be uploading shortly. 

The new version is available here:  https://www.sefaria.org/Genesis.1?ven=Il_Pentateuco._Traduzione_italiana_di_Samuel_David_Luzzatto%2C_1872_%5Bit%5D

Please continue uploading (from chapter 12 onward) using the above version.

Sincerely,

Shmuel

**Comment by MattiaHalevi** [comment]
Hi, 

thank you for fixing.
I am sorry I see this too late. I checked the link. I am not sure why, but some parts of chapters look correctly translated into Italian, while some others are still in Hebrew. Why is it so? Do I have to translate those parts again?

**Comment by ShmuelW** [comment]
Chapters 1-11 are currently being uploaded. It may take up to 30 minutes to show on your end. 
Any new material beyond chapter 11 should be uploaded to the same version.

Thanks, and apologies for any misunderstanding...
