### ISSUE TITLE
Superfluous versions

### ISSUE THREAD

**Issue by MattiaHalevi** [Sefaria/Sefaria-Project#525]
While I was coping some new Italian translations in Exodus, two superfluous versions have been created by mistake.

The first one is listed as English translation: (_Il Pentateuco. Traduzione italiana di Samuel David Luzzatto, 1872 [it]A Mosè poi disse: Sali al Signore, tu ed Aronne, Nadàv ed Avihù, e settanta degli anziani d’Israel, e vi prostrerete da lungi._).

The second one is listed as English translation: (_Il Pentateuco. Traduzione italiana di Samuel David Luzzatto, 1872 [it]Nel mese terzo dall’uscita degl’Israeliti dalla terra d’Egitto, in questo giorno [cioè nel primo del mese, nel dì della luna nuova; poiché la voce ebraica che vale mese, significa propriamente_ ).

These two should be removed.
Thank you and sorry for my mistake.

**Comment by JonMosenkis** [comment]
For issues regarding site content, please send an email to corrections@sefaria.org.
