### ISSUE TITLE
Reporting text and Punctuation mistakes

### ISSUE THREAD

**Issue by ezosher** [Sefaria/Sefaria-Project#534]
Hey Guys,

Thanks for this amazing platform and Yeshar Koach for all the work truly amazing keep it up.

I'v couldn't find any docs referring to contributing to text and Punctuation mistakes that where found.
please let me know cheers. 

I can refer you to one found here [Parashat Nesim](https://www.sefaria.org.il/Siddur_Sefard%2C_Nissan%2C_The'Nasi'_Readings.19?lang=he&with=all&lang2=he)

where text says 
שְׂעִיר עִזִּים אֶחָד לְחַטָּאת

suppose to be end of phrase;
cheers,

keep it up

**Comment by ShmuelW** [comment]
Hi,

Thanks for pointing it out!

We've now corrected the text by adding a colon after the phrase.
The corrected version will be available in the Android/iOS app upon the next library sync. 

Please feel free to report future textual errors to corrections@sefaria.org 

Community translations are open for editing by any registered Sefaria user.

Sincerely,

Shmuel Weissman
MANAGER of TEXT ACQUISITION & TEXT QUALITY
shmuel@sefaria.org | sefaria.org
