### ISSUE TITLE
Some comments in the /texts API are broken up letter by letter

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#541]
https://www.sefaria.org/api/texts/Shabbat.51b?commentary=1 lists a Mesorat Hashas commentary for the ref `Shabbat 56b:20-57a:1` that has a `text` attribute with 575 items, and an `he` attribute with 90 items. Looking at them, it appears that something is causing them to break up each character into individual strings (except for the first `he` item, which has some HTML in it).

[Requesting the ref as a regular text](https://www.sefaria.org/Shabbat.56b.20-57a.1) shows the text as normal.

**Comment by ronshapiro** [comment]
The same is visible for https://www.sefaria.org/api/texts/Shabbat.41a?commentary=1 for the ref to `Ketubot 110b:25-111a:1`.

I wonder if there's something related to the fact that both of these span multiple amudim.

**Comment by ronshapiro** [comment]
Any pointers for where I could look to see why this is happening? I continue to see examples of it, and it results in very strange data on my end.

The current example I saw was https://www.sefaria.org/api/texts/Shabbat.117a?commentary=1 with the comment for Shabbat 6a:16-6b:1. But I've also seen it for comments to Shulchan Arukh

**Comment by nsantacruz** [comment]
@ronshapiro this has been fixed with #644 which will hopefully be deployed in a few days.
