### ISSUE TITLE
bracket consecutive qere words together

### ISSUE THREAD

**Issue by bdenckla** [Sefaria/Sefaria-Project#545]
E.g. I suggest [מַה־זֶּ֣ה] not
[מַה־]
[זֶּ֣ה]
in [Exodus 4:2](https://www.sefaria.org/Exodus.4.2?lang=he&aliyot=0).

(I had to put each on a separate line to avoid vexing problems with getting RTL text to work in GitHub-flavored Markdown.)

I particularly suggest this for words separated by a *maqaf*, as in the Exodus 4:2 example above.

But I think it would be better for words separated by a space, too.

**Comment by JonMosenkis** [comment]
Thanks for reaching out.
As outlined in our FAQ, textual corrections are best handled by sending an email to corrections@sefaria.org.

**Comment by bdenckla** [comment]
Ok thanks I will try to raise this issue via corrections@sefaria.org.

I suspect the feature would be added in the code that converts tanach.us sources to whatever internal format is used by Sefaria. So this issue is sort of "half code, half data" if that makes any sense. (By tanach.us I mean UXLC: the Unicode/XML Leningrad Codex.)

Unless that conversion from tanach.us to Sefaria was a one-time thing and Sefaria's sources are now developing independently from tanach.us (possibly manually taking updates from tanach.us). In that case this issue is squarely in the "data" camp since that conversion code from UXLC presumably won't ever be run again?

**Comment by edamboritz** [comment]
Hi, 
I'm not entirely sure if this will satisfy your question, but I hope so- 
First, yes. The Data conversion from tanach.us is not an ongoing procedure. It was a process that ran once and we try to stay updated when there are significant changes, also independently, from user corrections (though the Leningrad representation there is still the standard). 
This leads me to the fact that the source of those separate quere word wrappings is actually the convention of tanach.us itself. It was not a decision we made on our side.  

Hope this answers your technical question and thanks again for the feedback!

**Comment by bdenckla** [comment]
> the source of those separate quere word wrappings is actually the convention of tanach.us itself

Thanks for your replay @edamboritz.

I disagree that the "per word" brackets that Sefaria shows the user are a convention stemming from tanach.us itself. They stem only from Sefaria's somewhat literal (IMO overly literal) presentation of tanach.us XML to the user.

Note that tanach.us itself, when it renders its XML for the user, does not expose this per-word underlying representation of qere. For instance for the example we've been discussing, here's how it renders (in my browser at least):

![image](https://user-images.githubusercontent.com/941315/80979175-047c9980-8df5-11ea-8743-55518dd7caf4.png)

Yes, in the XML from tanach.us the individual words are enclosed in `q` (*qere*) tags. And yes, it was *easiest* to turn each `q` tag into a square-bracketed word, when converting from tanach.us to Sefaria's internal format. And yes, it seems like Sefaria doesn't have much of a distinction between internal (underlying) representation and external (user-presented) representation, so perhaps Sefaria has painted itself into a bit of a corner with this (and other?) issues.

Perhaps there is an opportunity all the way "up" in Javascript to coalesce a span of individually bracketed words into a bracketed span of (unbracketed) words? And then the space after maqaf would need to be removed.

I don't know what Sefaria's underlying representation is, but judging from the JSON export, it seems like the only first-class structures preserved from tanach.us are that of chapter and verse. That's fine, but in that case perhaps you can take advantage of the "second class" (in-string) structure preserved from tanach.us in the form of brackets. I.e. you've effectively encoded `q` tags as brackets. By just showing each verse as is, you're sort of showing the user your internal representation, not a user-tailored representation.
