### ISSUE TITLE
Make A/B of Talmud Dafs Case-insensitive

### ISSUE THREAD

**Issue by DovOps** [Sefaria/Sefaria-Project#562]
https://github.com/Sefaria/Sefaria-Project/blob/77a38d08fbc4572d7859ee9848c2639ef9f4aae8/sefaria/model/text.py#L2604-L2607

It would be nice to tolerate 101A in addition to 101a when referencing Dapim of talmud. I don't see this being difficult to support by lc()ing the input strings in the referenced method, but I cannot get a reliable environment up and running to make the change and test/submit PR.

Success criteria:  Something like 'Shabbat 101B' behaves just like 'Shabbat 101b' 

At present, 'http://sefaria.org/Shabbat%20101B' redirects to a 404.   If this is modified, it would redirect to https://www.sefaria.org.il/Shabbat.101b

**Comment by nsantacruz** [comment]
The other place that would need to be modified is here. We have have Python tests which cover these cases extensively so the change should be easy for anyone interested in trying.

https://github.com/Sefaria/Sefaria-Project/blob/77a38d08fbc4572d7859ee9848c2639ef9f4aae8/sefaria/model/schema.py#L1954-L1957

**Comment by DovOps** [comment]
Thanks. May give it a go, just need to sort out my local dev env. Has anyone tried getting the environment  setup in gitpod or codespaces or the like?

**Comment by nsantacruz** [comment]
I haven't heard of anyone trying to do this.

**Comment by yairm210** [comment]
It seems that this has already been solved ;)

**Comment by blockspeiser** [comment]
Fixed recently, thanks @stevekaplan123 .
