### ISSUE TITLE
Browser Page Focus

### ISSUE THREAD

**Issue by YehudaGefen** [Sefaria/Sefaria-Project#565]
When any Internet Browser page displays, cursor keys, i.e. <up>, <down>, <page up>, <page down> should be available. They are not when an Sefaria page displays. This is true in Chrome, Edge, Firefox and Opera. Other sites do not exhibit this behavior. Clicking within a page restores scrolling by keystroke. Tab key clicking to the page also corrects this. Does the Sefaria page layout set the focus elsewhere and for a purpose?

**Comment by rneiss** [comment]
It's in part part of our obligation to try and adhere to best practices for allowing folks who navigate Sefaria with Assistive Devices to have the best experience, particularly for those users who navigate with a screen reader.

https://blog.sefaria.org/blog/2017/11/10/assistive-technology-on-sefaria
