### ISSUE TITLE
link to Google Drive

### ISSUE THREAD

**Issue by pjwrabbi** [Sefaria/Sefaria-Project#566]
I recently changed to a new job with a new professional email.  My account is in my personal name and personal account.  However, when Sefaria exports documents it goes to the Google drive of my former professional account.
I have updated my Sefaria profile, but that has not helped.

Please help be get this to work properly!

**Comment by rneiss** [comment]
1. Go to your Google Account that is linked with Sefaria.
2. On the left navigation panel, select Security.
3. On the Third-party apps with account access panel, select Manage third-party access. 
4. Select the site or app you want to remove.
5. Select Remove Access.
