### ISSUE TITLE
Texts API always returning HE text with te'amim/vowels

### ISSUE THREAD

**Issue by jddphd** [Sefaria/Sefaria-Project#569]
Hello,

I have been using the Texts API to pull back text with the te'amim and without the te'amim. 

Two weeks ago, I could use the following calls:

// $sefaria_url ='https://www.sefaria.org/api/texts/Deuteronomy.3.23-25?lang=he&version=2'; // WITH vowels and te'amim
// $sefaria_url = 'https://www.sefaria.org/api/texts/Deuteronomy.3.23-25?lang=he&version=4'; // withOUT vowels and te'amim

When I tried today:

1. I see now that regardless of the specification of version, the text always comes back with vowels and te'amim.
2. The versions have changed. For a simple call (one that does not span multiple chapters), the "TANAKH WITH TEXT ONLY" is now version=3 instead of version=4. For complex calls (spanning multiple chapters), it is still version=4. That said, because of problem 1, it doesn't matter what I put.

Can someone look into this please?

Thanks,
- JD

**Comment by nsantacruz** [comment]
Hi JD,

I don't believe we have a `version` URL parameter on the Texts API. 
You may be confusing this the version path parameter which you specify like this:

```
/api/texts/:ref/:lang/:version
```

where `:` indicates a variable name. For example

sefaria.org/api/texts/Deuteronomy.3.23-25/he/Tanach_with_Text_Only

will return the version of Tanakh without te'amim and vowels.

Here's the documentation for reference https://github.com/Sefaria/Sefaria-Project/wiki/API-Documentation#get-apitextsreflangversion
