### ISSUE TITLE
Handle array index changes

### ISSUE THREAD

**Issue by mattpolanieckidev** [Sefaria/Sefaria-Project#583]
Hello,

Every now and then the /calendar items shift so instead of calendar_items[2].url pulling the daf, it loads another book (like 929).

How can I consistently target the category of "Talmud"?

**Comment by edamboritz** [comment]
Hi, if you are referring to the calendar api, the order of the calendar items is incidental and should never be relied upon. 
If you want the daf yomi, its best to filter the list for the object that has a `title.en` value of "Daf Yomi".
