### ISSUE TITLE
user should be able to open multiple texts

### ISSUE THREAD

**Issue by eitan613** [Sefaria/Sefaria-Project#588]
Sometimes it is helpful to have multiple texts open at once to compare them. However right now you can only do this with limited texts that are connected somehow to the original one like a commentary. But the user might want to (I often do) open a completely different text next to it. not such a big issue because you can always open a new tab and put them next to each other like that but would be nice if it was a feature here

**Comment by nsantacruz** [comment]
Hi @eitan613 ! You can currently do this by opening the commentary panel and clicking "Other Text". This will allow you to choose any text to compare to the one you're reading.
