### ISSUE TITLE
Bizarre empty results dependent on parameter order

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#597]
I'm seeing some bizarre results when I query the following URL:

https://www.sefaria.org/api/texts/Berakhot.24b?commentary=1&wrapLinks=0&pad=0

`text` and `he` arrays are returned back empty. I don't see it for any other ref though. Additionally, if I make _any_ change to the URL, everything works fine. Adding a `&` to the end, changing the parameter order, adding `&foo=bar` all work.

Maybe some request had an error and the empty results are being cached? Or is it something about this request in particular?

**Comment by nsantacruz** [comment]
I am seeing `text` and `he` arrays with content using that URL. It is possible you're right that an erroneous API request was cached but it no longer seems to be an issue.

**Comment by ronshapiro** [comment]
Is it worth checking if this can be a broader issue?

**Comment by nsantacruz** [comment]
I did a cursory look over the path this API went and I don't see any issues that pop out. Without a way to reproduce this, I will keep this closed. If you see this issue again, we can reopen and see if there is a clear way to reproduce.

**Comment by ronshapiro** [comment]
This happened to me again: 

https://www.sefaria.org/api/texts/Tamid.25b?commentary=1&wrapLinks=0&pad=0 works
https://www.sefaria.org/api/texts/Tamid.25b?commentary=1&pad=0&wrapLinks=0 has no text or commentary

**Comment by EliezerIsrael** [comment]
I hate to say it, @ronshapiro, but I'm getting the same results from those two calls. 

```
$ diff <(curl https://www.sefaria.org/api/texts/Tamid.25b?commentary=1&wrapLinks=0&pad=0) <(curl https://www.sefaria.org/api/texts/Tamid.25b?commentary=1&pad=0&wrapLinks=0)
$
```

**Comment by ronshapiro** [comment]
That's probably expected - after the caching window (whatever it is) has passed, it's likely that whatever errors arose simply get fixed.

I think the fix to the underlying issue is to make sure that whatever error is causing the empty arrays propagates so that the entire request is an error, and therefore not cached.

**Comment by ronshapiro** [comment]
I'm seeing this again with Tamid 25b.

And I've seen it in other places.

I don't know if there's much to debug for a particular ref/combination order because it seems like the results are being cached and an intermittent issue is causing the text results to be empty.

Perhaps the best way is to add some logging & alerting for when a ref has no text when it is expect to. Then you can inspect the first (uncached) request that sends the alert and see what's going on?
