### ISSUE TITLE
Bug: Problem navigating away from Jastrow after a word is not found in dictionary

### ISSUE THREAD

**Issue by jayek0** [Sefaria/Sefaria-Project#598]
When I search for a word in the Jastrow dictionary that Jastrow cannot find/is not in the dictionary I get an error page that reads 

’Something went wrong! Please use the back button or the menus above to get back on track.
Error Message: Word not found in Jastrow’

When I attempt to do as it asks, and hit the back buttons to exit I stay trapped on the error page indefinitely until I go back to the home page by editing the URL in the browser search bar.

Platform: Chrome on a macbook.

**Comment by HadaraRachel** [comment]
Thank you for reporting. for future bug reports please email hello@sefaria.org
