### ISSUE TITLE
Nuxt site - Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by izzygld** [Sefaria/Sefaria-Project#600]
We tried adding the script to our Nuxt site. ([following the instructions here](https://github.com/Sefaria/Sefaria-Project/wiki/Sefaria-Auto-Linker#embed-code))

Getting the following errors:

```
Uncaught ReferenceError: module is not defined
    at linker.js:15
    at linker.js:15
    at linker.js:549
```

Our Stack
"vue": "2.6.12"
"nuxt": "^2.12.0"

Any help would be appreciated.

thanks

**Comment by nsantacruz** [comment]
Thanks for the feedback. Looking at the line with the error, I realize we may not have properly been checking for the existence of `module.exports` properly. I just pushed this change which hopefully will fix the issue: https://github.com/Sefaria/Sefaria-Project/commit/41b65fff3d2754ee2fdea38ad6836ccf77517cbd

This fix will hopefully be live in the next few days.

**Comment by nsantacruz** [comment]
This should now be live. I'm closing the issue but please comment if it's not fixed for you.
