### ISSUE TITLE
Calendar API: Incorrect Parashat Hashavua

### ISSUE THREAD

**Issue by M-Zuber** [Sefaria/Sefaria-Project#604]
There seems to be a bug in the calendar api where it will just randomly return `Vayeilech`
For example:
https://www.sefaria.org/api/calendars?day=1&month=07&year=2014

**Comment by edamboritz** [comment]
Hi, I believe that is an unfortunate consequence of Sefaria's parashat hashavua calendar data only starting in 2016. Vayeilech of that year is in fact our first piece of data. 
Interesting, because we haven't had a request for historical data up until now.

**Comment by M-Zuber** [comment]
I don't actually **need** that data, but I was playing around and what looked like weird behavior to me
