### ISSUE TITLE
Creating aliases to match Sefarias exact spelling

### ISSUE THREAD

**Issue by izzygld** [Sefaria/Sefaria-Project#606]
What's the simplest way to match/create Aliases to Sefaria spelling?

Example: Avot (1:2) = TRUE vs Avos (1:2) = FALSE.

This issue might be linked to [ #577](https://github.com/Sefaria/Sefaria-Project/issues/577)

**Comment by JonMosenkis** [comment]
Use the `regexes` API:
https://www.sefaria.org/api/regex/<titles>
Where `titles` is a piped list of the titles in question.
You'll get a key for all the valid name schemes. The value will be a regular expression which will allow you to then match all valid spellings for said title.

Unmatched titles will be listed in an array under the `error` key.

**Comment by JonMosenkis** [comment]
Here's an example query:
'https://sefaria.org/api/regexs/Avot|Avos|Blavot'

**Comment by MDjavaheri** [comment]
> Here's an example query:
> 'https://sefaria.org/api/regexs/Avot|Avos|Blavot'

This answers the matching part of his question, not the how to create part.
