### ISSUE TITLE
Add chapter subheadings to Rabbi Bleich's books

### ISSUE THREAD

**Issue by MDjavaheri** [Sefaria/Sefaria-Project#611]
## Context
For the students of Rabbi J. David Bleich, it can be challenging to find articles in his _Contemporary Halakhic Problems_ on a specific topic. The tables of content headings are sometimes too general.

## Example
For example, I'm learning Hilchot Gittin and want to see what he has to say on the topic, but in order to find his articles on Gittin, I have to open each book and read through the table of contents, whether it be in print or on Sefaria. In some cases, even that isn't enough, because the chapter headings are too ambiguous ("Kashrut," "Marriage," etc.) 
[This is what I currently see on Sefaria](https://www.sefaria.org/Contemporary_Halakhic_Problems,_Vol_I?lang=bi)
> 
> Preface
> Introduction, The Methodology of Halakhah
> Part I 
> Prelude
> CHAPTER I Israel
> CHAPTER II Sabbath and Festivals
> CHAPTER III The Synagogue
> CHAPTER IV Kashrut
> CHAPTER V Medical Questions

And [this is what I could be:](https://github.com/MDjavaheri/rav-bleich-index/blob/master/tocs/vol1-toc.txt)

> CHAPTER I Israel: 
> -Settlement in Israel 
> -Settlement in Israel in Face of Danger 
> -Aliyah Against Parental Objections 
> -War and the State of Israel 
> -Hijack Victims 
> -Extradition 
> -Guard Duty on the Temple Mount 
> -Imprisonment or Death for Convicted Terrorists 
> -Sale of Israeli Real Estate to Non-Jews 
> 
> CHAPTER II Sabbath and Festivals: 
> -Sale of Commercial Enterprises to Sabbath Violators 
> -Sabbath Elevators 
> -Erev Pesaḥ Which Occurs on Shabbat 
> -Mazah on Erev Pesaḥ 
> -Egg Mazah on Erev Pesaḥ 
> -Mukzah 
> -Sale of Hamez by Tourists 
> -Baby Formula on Passover 
> -A Responsum from behind the Iron Curtain 
> -Shaving on the Intermediate Days of Festivals 
> -Temporary Residents in Israel and Yom Tov Sheni 
> -Yom Tov Sheni 
> 
> CHAPTER III The Synagogue: 
> -Apartments over a Synagogue 
> -Prayer from the Bimah 
> -Removal of Torah Scrolls 
> -Yissokhor or Yissoskhor? 
> -Rabbinic Contracts 
> -Seliḥot Services 
> -Dual Bar Mitzvahs 
> -Bat Mitzvah Celebrations 
> -Women in a Minyan? 
> 
> CHAPTER IV Kashrut: 
> -Single Sterilizer for Both Meat and Dairy Utensils 
> -Garfish and Scad 
> -Cold-Water Plucking 
> ...
> 
## Solution
Can Sefaria alleviate this challenge by adding the chapter subheadings to the tables of contents?
[Here's a list ](https://github.com/MDjavaheri/rav-bleich-index) filtered out of Sefaria's texts, if that helps. 

## Going Forward
I guess tagging the articles with the appropriate topics would also be helpful, but my experience with topics is shallow.

**Comment by JonMosenkis** [comment]
This is a great idea and would be a major improvement to the book on Sefaria! There are a couple technical "gotchas" here that might delay the deploy of this feature though. 

Thanks so much for raising awareness to this!

**Comment by MDjavaheri** [comment]
Thank you! Rabbi Bleich will be appreciative once it's possible to work on this, as well.
