### ISSUE TITLE
Wrong parsha shown Jan. 9, 2021

### ISSUE THREAD

**Issue by mcoblenz** [Sefaria/Sefaria-Project#613]
https://www.sefaria.org/texts showed the wrong current parsha at 11 AM EST on Jan. 9, 2021. The correct parsha is Shemot (indeed, the calendar API agrees with this: https://www.sefaria.org/api/calendars?day=9&month=01&year=2021), but the web site shows Vaera.

**Comment by edamboritz** [comment]
Hi, We've been unable to reproduce the issue so far and have not heard any other feedback regarding it. The code that powers the API and the texts page is actually largely the same, so it's additionally odd. We'll be keeping an eye out for this potential bug but please do let us know if you encounter it again.
