### ISSUE TITLE
/api/texts variant that allows requesting multiple refs

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#616]
The `/api/texts` endpoint has a `multiple` parameter that allows requesting multiple neighboring refs. It's implemented by iterating on the `"next"`/`"previous"` attributes of the single text response:

https://github.com/Sefaria/Sefaria-Project/blob/170c8b828fc11d60b2f89b54214dc670e0f5921e/reader/views.py#L1301-L1308

I'd like to propose a similar API that can provide a list of (potentially unrelated) refs and returns the data in the same format as using the `multiple` param. 

One potential use case is using the `/api/links` endpoint, applying a filter to some of the connections, and then requesting the desired refs in one request instead of N requests. An alternative is to just request `?commentary=1` and then filter on all of the commentaries, but that doesn't always return valid responses at the moment (#573), and even if it did, given the type of filtering, it may not be advantageous for the client or the server to return every possible result.

It seems like the even Sefaria site could benefit from this. When viewing all of the commentaries for a given line/verse, separate GET requests are made for each link to that ref. 

This would benefit clients and the server by reducing the number of https handshakes. It could also benefit clients that aren't operating in a multithreaded context or that want to be able to limit the amount of total outbound requests in a given period.

I'm indifferent to what the request would look like - perhaps one of the following:
- `/api/texts/?refs=Genesis.1.1&refs=Exodus.2.2` (n.b. that there is no "single" ref here
- `/api/texts/Genesis.1.1?andRef=Exodus.2.2&andRef=Leviticus.3.3`
- `/api/texts/Genesis.1.1?additionalRefs=Exodus2.2@SOME_TYPE_OF_DELIMITER@Leviticus.3.3`

These would start to run into some limits around [URL length](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) but that may actually provide some good natural limiting on the amount of refs that can be retrieved in a single request.

The only parameters that may be awkward to use here are `versionEn` and `versionHe`. Users could shard requests by version types if necessary, though I imagine most requests are version-less.

I'd be happy to implement this if there's agreement on the feature and what the endpoint should look like.

**Comment by nsantacruz** [comment]
Interesting! I could see a use case for this.
We do have an api endpoint sefaria.org/api/bulktext which allows you to request just the text of an arbitrary list of refs. I'm seeing it's not documented right now so I'll try to add documentation for it.
Here's an example call https://www.sefaria.org/api/bulktext/Genesis.1.1|Exodus.1.1

This API solves the use case you mentioned of calling `/api/links` and then bulk requesting the text of all the links.

**Comment by ronshapiro** [comment]
Ah, that's nifty! 

What does `useTextFamily` mean? It has my desired output (ref ranges not flattened to a string) but I'd love to make sure that that's not just a side effect of the comment here:
https://github.com/Sefaria/Sefaria-Project/blob/170c8b828fc11d60b2f89b54214dc670e0f5921e/sefaria/views.py#L316-L317

**Comment by nsantacruz** [comment]
yeah, the point of `useTextFamily` is to not flatten the jagged arrays! I'm closing this issue then.
