### ISSUE TITLE
/api/texts 500s for Yerushalmi spanning refs that cross over chapters with context=0

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#634]
The [corresponding refs](https://github.com/Sefaria/Sefaria-Project/issues/628) for Yerushalmi Shekalim [5a](
https://www.sefaria.org/api/texts/Jerusalem_Talmud_Shekalim.1.4.35-2.1.13?context=0), [13a](https://www.sefaria.org/api/texts/Jerusalem_Talmud_Shekalim.4.4.42-5.1.10?context=0), [19a](https://www.sefaria.org/api/texts/Jerusalem_Talmud_Shekalim.6.4.31-7.2.5?context=0), and [21a](https://www.sefaria.org/api/texts/Jerusalem_Talmud_Shekalim.7.3.39-8.1.6?context=0) when requested with `context=0` return a `500` error.

These all including refs that span multiple chapters. I got the mapping of daf-to-ref by inspecting the Daf Yomi tab of https://www.sefaria.org/Jerusalem_Talmud_Shekalim.

**Comment by EliezerIsrael** [comment]
@ronshapiro Thanks for reporting this.  I believe that the issue was fixed with https://github.com/Sefaria/Sefaria-Project/commit/8faae8d2ea5a5ae4079b47d6d81b1984972d3f2a

**Comment by ronshapiro** [comment]
Thanks! Looks great on my end
