### ISSUE TITLE
Bug on iOS

### ISSUE THREAD

**Issue by ijksail** [Sefaria/Sefaria-Project#652]
After being directed out of the app to the browser, there is a dead end to get back to app. The open - cancel window is unresponsive. The app had to be deleted and re-opened. 

https://user-images.githubusercontent.com/5099332/118863290-b7a71c00-b8ac-11eb-88d1-a8910776666b.MP4

**Comment by HadaraRachel** [comment]
Thank you for reporting! this has been fixed. 
for any further bugs/features please email hello@sefaria.org
