### ISSUE TITLE
Bug - copying 

### ISSUE THREAD

**Issue by elishabenabbuyah** [Sefaria/Sefaria-Project#653]
When copying from the Talmud (and maybe other texts?) the letters on the side of the page that direct one to commentaries etc. get picked up by the "copy" command so that there are random extra letters strewn throughout the pasted text.

**Comment by HadaraRachel** [comment]
Thank you for reporting! This should be fixed. 
For any further bugs/feature requests please email [hello@sefaria.org](mailto:hello@sefaria.org)
