### ISSUE TITLE
Ecclesiaste - double entry

### ISSUE THREAD

**Issue by hymanaharon** [Sefaria/Sefaria-Project#694]
There is a double entry Ecclesiaste and Ecclesiastes

**Comment by edamboritz** [comment]
Hi, thanks for pointing this out! We have fixed the issue.

In the future, it would be most helpful if you could point to the specific place you are seeing issues, either via url or more detailed description. 
Content corrections can also be sent to corrections@sefaria.org as described here: https://github.com/Sefaria/Sefaria-Project/wiki/How-to-Report-a-Mistake.

Thank you!
