### ISSUE TITLE
Duplicative connections

### ISSUE THREAD

**Issue by herlands** [Sefaria/Sefaria-Project#73]
Certain Sefaria pages have many duplicative connections. For example, see http://sefaria.org/Pirkei_Avot.3 for duplicative connections to Tanakh. I suggest two features:

1) Duplicative comments should be detected when a user attempts to add a new connection. 
2) A script to crawl through Sefaria and remove duplicative comments. From what I understand, this can only be done by Brett.

**Comment by EliezerIsrael** [comment]
I believe this is no longer an issue.
