### ISSUE TITLE
Lashon Kodesh /Aramic Dictionary

### ISSUE THREAD

**Issue by PleaseSmileToday** [Sefaria/Sefaria-Project#737]
Is it possible to get a dump of all text files,
And make a txt file containing one of each word.
So that i can have a Lashon Kodesh /Aramaic spell checker for word.
Word's built in Hebrew is missing a lot of words.
I'm also  working on an OCR project, and want to only allow words that are in a custom dictionary, so that i get much better results.
(I'm using Abby Fine Reader 15) 
Any guidance /feedback would be appreciated.
Thank You.

**Comment by nsantacruz** [comment]
Hi @PleaseSmileToday, thank you for reaching out. Our Github issues page is meant for issues relating to our site. It sounds like you are working on a personal project (which sounds interesting!) but we don't answer general questions on how to accomplish a project. If you have specific technical issues with our site or API, please reach out to hello@sefaria.org and we'll try to help with your issue.

You can find a complete dump of our texts in this [this repo](https://github.com/Sefaria/Sefaria-Export).
