### ISSUE TITLE
Notifications Screen

### ISSUE THREAD

**Issue by shman** [Sefaria/Sefaria-Project#738]
I'm not sure if this is a replicable problem, but it certainly has been giving me a lot of headaches.
When I navigate to /notifications, I see my most recent notifications - that's all good. (See attached picture...)
However, when I scroll down and the notifications load past about two years, the console starts acting up and giving me lots of errors from React and the screen goes blank. (I don't particularly care about the error - I just really want to retrieve some notifications from 6 years ago!!) Screenshot attached.
![Screenshot 2022-01-17 193111](https://user-images.githubusercontent.com/6728137/149851282-6413e9d7-4978-4812-9ad3-c1a83ae5117e.png)
![Screenshot 2022-01-17 193256](https://user-images.githubusercontent.com/6728137/149851284-cfd36b99-7bbb-44b8-9b27-8601d1d43118.png)

**Comment by shman** [comment]
Let me add - even if this isn't solved, I would very much appreciate if someone could grab my notifications from the backend and send them to me...

**Comment by nsantacruz** [comment]
Hi @shman, for privacy, best to reach out to hello@sefaria.org with the email that you use to sign in to Sefaria and then we can send you your notifications. 
And that will also help us debug this issue!
