### ISSUE TITLE
Yiddish translation

### ISSUE THREAD

**Issue by alephreish** [Sefaria/Sefaria-Project#761]
Currently, the Yehoyash Yiddish translation of Tanakh behaves counterintuitively. Choosing Yiddish translation doesn't add the Yiddish text as a translation as with other languages, but replaces the Hebrew text instead:

![Screenshot from 2022-02-20 20-07-28](https://user-images.githubusercontent.com/2794008/154857427-50569e9d-1e33-4aed-a75e-27d99719dcf5.png)

![Screenshot from 2022-02-20 20-07-28_2](https://user-images.githubusercontent.com/2794008/154857428-342d3043-cf19-4d37-bffd-ede3829832c3.png)

To read both in parallel one has to open two separate panels.

**Comment by edamboritz** [comment]
Hi, you are correct- 
Unfortunately that is a current limitation of our software. 
All Semitic / RTL translations actually replace the Hebrew in the main panel. 

Currently there are two workarounds- one solution is as you suggested, the other is to click the translation title in the connections panel itself, which will open the text in the connections panel and follow along as you scroll the main text.
