### ISSUE TITLE
Bug:  מדרש תנחומא, בראשית א׳:א

### ISSUE THREAD

**Issue by AriAbr** [Sefaria/Sefaria-Project#766]
The double quotes are messing with the text direction. It should be 

אם אתה עושה חי"ת ה"א, אתה מחריב את העולם, כֹּל הַנְּשָׁמָה תְּהַלֵּל יָהּ (תהלים קנ, ו), אם אתה עושה ה"א חי"ת, אתה מחריב את העולם.

https://www.sefaria.org.il/Midrash_Tanchuma%2C_Bereshit.1.1?ven=Midrash_Tanhuma-Yelammedenu,_trans._Samuel_A._Berman&vhe=Midrash_Tanchuma_--_Torat_Emet&lang=he
![image](https://user-images.githubusercontent.com/41592004/155878852-03d43120-6201-4ed1-b7e3-41f9b9b11802.png)

**Comment by edamboritz** [comment]
Hi! 
Can I ask you to send this report via email  as described [here](https://github.com/Sefaria/Sefaria-Project/wiki/How-to-Report-a-Mistake) so that our Text Quality staff can properly see and address it? 

 Thank you!

**Comment by AriAbr** [comment]
@edamboritz I don't think this is a text quality issue. The text is correct, but the left-to-right display is messed up. Should I still report it as a text mistake?

**Comment by edamboritz** [comment]
Ah! 
I'm clearer on your meaning now. 
We will handle it. Thanks for reporting!
