### ISSUE TITLE
An option not to display the name of God

### ISSUE THREAD

**Issue by noamraph** [Sefaria/Sefaria-Project#767]
Hi,

My friend got upset when he saw the four-letter name of God appear on his screen. It would be nice to have an option to replace it, say, by ידוד (this is what פרוייקט השו"ת did, until the used יקוק, which I find really ugly).

Would you accept a pull request that adds this option?

Thanks for this great project!
Noam

**Comment by emrichter** [comment]
I would also appreciate such a feature. Would be nice to do the same for all names (Elokim, Shakai, etc.), not only the shem H'

**Comment by rneiss** [comment]
We already have such a feature on our [old source sheet editor](https://github.com/Sefaria/Sefaria-Project/blob/3fb1789a115bc320bf614862a3cadc43965a66f4/static/js/sheets.js#L3629) (look in the toolbars under `format > divine names`) and on the beta of our [new editor tool](https://github.com/Sefaria/Sefaria-Project/blob/0c6edcef0945659fb055bb4b96713afeaf606397/static/js/Editor.jsx#L336) (see the sidebar menu under tools), as we recognize that many folks may come to print these documents. 

We currently do not have plans to implement this across the library in the online reader view.

**Comment by emrichter** [comment]
Thanks for the update! Is actually would need it for API calls. Is this available in the API?

**Comment by edamboritz** [comment]
Hi, no, similarly to our Reader, it's not available on the API. Though I believe you can adapt the code we use in the editor to replace the names to replace it on the API results as well. Or use your own custom replacement logic.
