### ISSUE TITLE
Biblical search results are missing trop only for the word(s) you search for

### ISSUE THREAD

**Issue by freilich-am** [Sefaria/Sefaria-Project#782]
I noticed the following today: if I type in a hebrew word to search for (e.g. הָרָצִים֮) I'll get some results. Include some from Tanakh. All the results from tanakh will show up with nikkud for all words and trop for all words _except_ the ones I searched for. This is true for phrases as well. It's true if the input includes the trop or not. 

I think it would be nice if all the trop was there. Mostly I'm curious what the difference between the nikkud and trop in this respect. 

[Not that it's particularly surprising but I checked and this is also true for ta'amei emet.]
[Edit: Could it be a font thing? Probably the bold loses trop support, right?]

Examples:
<img width="753" alt="Screen Shot 2022-03-14 at 9 29 08 PM" src="https://user-images.githubusercontent.com/43653770/158288346-aa119324-7d24-4758-a3b7-a35d92f96478.png">
<img width="771" alt="Screen Shot 2022-03-14 at 9 31 21 PM" src="https://user-images.githubusercontent.com/43653770/158288348-a19c3793-5fe4-45a3-a402-5d07839a673b.png">

**Comment by freilich-am** [comment]
I confirmed that if I paste from that text the trop is _there_. Probably a font issue then, yeah?

**Comment by edamboritz** [comment]
Hi, we will look into this. Thanks for pointing it out!

**Comment by nissamai** [comment]
@edamboritz - I am assuming we did not decide this was urgent but just to confirm why this is happening: TaameyFrankCLM-Bold.ttf in [/static/fonts/Taamey-Frank](https://github.com/Sefaria/Sefaria-Project/tree/master/static/fonts/Taamey-Frank) is missing the unicode glyphs for trop markers (TaameyFrankCLM-Medium.ttf has them).

**Comment by HadaraRachel** [comment]
@nissamai that is confirmed. We have noted the bug previously, but for several reasons decided to postpone the fix. Thanks!
