### ISSUE TITLE
Add Sedarim Divisions

### ISSUE THREAD

**Issue by krixano** [Sefaria/Sefaria-Project#785]
The Sedarim divisions are an ancient tradition of section divisions that originated for the triennial cycle, and are now being used in some modern Hebrew Bibles (e.g. Koren's Jerusalem Bible and the new Magerman Tanakh). They are also shown in the Biblia Hebraica based on the Leningrad Codex as well.
These divisions are being used by the learning schedule "Tanakh Yomi" that is shown on the learning schedules page.

Below is more information about the Sedarim Divisions and the Tanakh Yomi schedule being used by sefaria (for anyone unaware):
https://en.wikipedia.org/wiki/Seder_(Bible)
https://www.tanachyomi.co.il/

I have noticed that the sedarim sections haven't been added yet, but also that there's been a new(-ish) feature added that lets you choose which divisions you want to use (like chapters vs. parsha in the tanakh). So my request is to add these Sedarim divisions as well.

**Comment by nsantacruz** [comment]
Hi, thank you for the information. As you said Sefaria does have the Tanakh Yomi learning schedule. We've also tried to add Sedarim as an alternate way of navigating Tanakh but have run into issues with Sedarim that span books (e.g. Shmuel, Melachim, Divrei Hayamim all of which are separated into two books on Sefaria). We don't currently have an easy way to get around this issue.

I've created a task to look into this issue again soon.
