### ISSUE TITLE
There's no way to search all source sheets

### ISSUE THREAD

**Issue by IlanElovitz** [Sefaria/Sefaria-Project#862]
There currently does not seem to be a way to search through all the source sheets people have made on Sefaria.

You can only search within these very small, arbitrarily assigned, and often redundant or overlapping categories, of source sheets. For Instance, to find source sheets on something specific relating to the Avot, one would have to look in all the separate 
categories: "forefathers", "the patriarchs", "Abraham," "Abraham Character," "Abraham Traits," etc. "Isaac," "Jacob," etc. and you'd still be missing many things that are just tangentially related but might still be very helpful to your inquiry.

I'm not sure why this is, because it makes it near impossible to find anything specific.
Why is this the case?

I could've sworn you used to be able to do this, am I wrong?

**Comment by nsantacruz** [comment]
Hi, the search bar in the top right of site searches all texts + all source sheets.
