### ISSUE TITLE
Selecting/Copying Text on Sefaria.org

### ISSUE THREAD

**Issue by goldbergmoshe** [Sefaria/Sefaria-Project#864]
Hi,

Your project is truly amazing.
However find it extremely un-user friendly copying and pasting from the Sefaria website, since it copies/selects the paragraph number and spaces when you try select the text. 

**Suggestion** 

When selecting only make the actual text selectable (it can be done as simply in css using something like user-select: none on .segment .segmentNumber - this works now on almost all browsers -webkit, -moz and still allows the click to focus on the paragraph). 

I can submit a PR if you are interested in this at all. It has become a real pain. This could even be an option in user settings just save in localStorage.

Hatzlocha

**Comment by goldbergmoshe** [comment]
This is what occurs currently on Sefaria when you try select text..

https://user-images.githubusercontent.com/82201261/171051359-71f42a34-67c7-4909-ac84-01500d03c930.mov

This is my suggestion for Sefaria (just added the user-select: none as described above on the .segmentNumber)

https://user-images.githubusercontent.com/82201261/171051366-ce964ea4-6bb1-469a-8838-b735ee02148d.mov

**Comment by edamboritz** [comment]
Ah it would seem the culprit is Safari. It has very partial support for this CSS directive. Thanks for bringing this to our attention!
