### ISSUE TITLE
Vocalised text for tractate Niddah and several others not available.

### ISSUE THREAD

**Issue by JamesRead5737** [Sefaria/Sefaria-Project#865]
I have noticed that for a number of tractates for the Talmud Bavli a vocalised text is not available for download from the sefaria website. For example tractate Niddah:

https://www.sefaria.org/Niddah

Why is this? Does a vocalised version of these tractates not exist? Is there any plans to produce them in the future?

**Comment by nsantacruz** [comment]
We're working with an [Dicta](https://dicta.org.il/) who is producing these vocalized versions of Talmud Bavli. This is currently a work in progress but they hope to finish the project in a few months (currently seems like 3-4 months). Once it is complete, we plan to upload the rest of the tractates to Sefaria.
