### ISSUE TITLE
Dependency issues with latest version of Python

### ISSUE THREAD

**Issue by Zacharymk1213** [Sefaria/Sefaria-Project#916]
On the latest version of Python the required version of Cython does not install due to use of a deprecated method namely of collections.Iterable instead of collections.abc.Iterable

**Comment by edamboritz** [comment]
Hi, the compatibility of Cython to Python is unfortunately not something we have any control over. Is there a Sefaria specific issue in this regard, in more detail, we can help you with?

**Comment by Zacharymk1213** [comment]
The issue seems to be with the specific old version of Cython that Sefaria requires. Can you look into whether a newer version would work?
