### ISSUE TITLE
Dictionary feature breaks copying

### ISSUE THREAD

**Issue by goldbergmoshe** [Sefaria/Sefaria-Project#967]
The new dictionary feature breaks copying commentary text on the web version. 
The reason for this is since you can't select commentary text without the dictionary opening. 
This should be dealt with since many people utilise Sefaria for preparing source sheets by copying commentary texts. 
A possible way to fix this would be to only call dictionary on right click and disable default context menu that doesn't really have much of a use in Sefaria anyway. 

Thanks.

**Comment by edamboritz** [comment]
Thank you for reporting! 
We are already aware of this bug and are working to resolve!

**Comment by goldbergmoshe** [comment]
Amazing. 
Also, you can't copy at all on the IOS version (haven't tested android version). 
Think you might have user-select:none on all the text which should be addressed. Since currently it is not possible to copy text from Sefaria on IOS. 

Maybe will take a look at the source code for iOS. 

Are you aware if this has been done intentionally and if there is the above css property active?

Thanks

**Comment by edamboritz** [comment]
The iOS issue is a separate issue. 
It was actually deliberate and is currently something we needed to implement in order to get other features working properly. 
You can share a text by long pressing and selecting "share" via the phone's regularÍ sharing feature.

**Comment by goldbergmoshe** [comment]
Thanks. Had a feeling that was the case.
