### ISSUE TITLE
Converting output to well known book formats

### ISSUE THREAD

**Issue by AviadBag** [Sefaria/Sefaria-Project#993]
Hi

Has anyone created a software that can convert one of Sefaria's formats (say, json) to an e-book like epub, mobi, etc?
If not, is there is anyway a documentation of Sefaria's formats, so I can create one myself?

תבורכו מן שמיא

(I also opened this issue on Sefaria-Export, but it seems that there is no much activity there, so I am posting it here as well)

**Comment by edamboritz** [comment]
Hi, 
Internally, Sefaria indeed uses json or json-like (via MongoDB) formats for storing our text and book (index) records. We do not use any bespoke technological format but do have our texts structured in a certain way to facilitate a system for referencing locations within the text (that generally conforms to real world usage).

You can look through previous projects using Sefaria to see if one suits your needs: 
https://www.sefaria.org/powered-by
https://www.sefaria.org/powered-by-sefaria-contest-2020
https://www.sefaria.org/powered-by-sefaria-contest-2021

However if you do not find what you are looking for, we would be very excited to see and we encourage you to take this project on!

You can find documentation about our API and texts in our github wiki: 
https://github.com/Sefaria/Sefaria-Project/wiki/The-Structure-of-a-Book-in-Sefaria
https://github.com/Sefaria/Sefaria-Project/wiki/API-Documentation
et all

Good luck!
